Enable Windows 7 IIS tests
dotnet/aspnetcore pull request #10168
Opened 2019-05-10 22:46 UTC by natemcmaster

Resolves https://github.com/aspnet/AspNetCore-Internal/issues/1942

Waiting on https://github.com/dotnet/core-eng/issues/5506, which should be resolved soon.

2019-05-13 15:42 UTC, jkotalik approved these changes
As long as it works!

2019-05-13 20:25 UTC, jkotalik requested changes
This is still currently skipping all tests on Win7. It looks like IIS Express and IIS are still not installed on the machines.
```
C:\Program Files (x86)\IIS Express\config\schema\ doesn't exist
C:\Program Files\IIS Express\config\schema\ doesn't exist
C:\Program Files\IIS Express\config\schema\ doesn't exist
C:\windows\system32\inetsrv\config\schema\ doesn't exist
```

```
Updated C:\Program Files (x86)\IIS Express\config\schema\\aspnetcore_schema.xml
Updated C:\Program Files\IIS Express\config\schema\\aspnetcore_schema.xml
Updated C:\Program Files\IIS Express\config\schema\\aspnetcore_schema.xml
Updated C:\Windows\system32\inetsrv\config\schema\\aspnetcore_schema.xml
```

This means the config folders don't exist, which are always present when IIS/IISExpress is installed.

This seems like an issue with the win7 agents.

2019-05-14 16:18 UTC, natemcmaster commented
> Waiting on dotnet/core-eng#5506, which should be resolved soon.

Was waiting on https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/1228?_a=overview, but that was merged yesterday, so I'll re-spin the PR checks now.

2019-05-14 16:18 UTC, natemcmaster commented
/azp run AspNetCore-helix-test

2019-05-14 18:28 UTC, natemcmaster commented
All tests were skipped still, so apparently queue updates haven't rolled out yet.

2019-05-15 18:03 UTC, dougbu approved these changes

2019-05-15 18:03 UTC, dougbu commented on eng/targets/Helix.Common.props
> +    <HelixAvailableTargetQueue Include="Windows.7.Amd64.Open" />
Let's hope you're right that dotnet/core-eng#5506 is done 😺

2019-05-15 19:01 UTC, natemcmaster commented
Helix update for Windows 7 is planned for today. Once that's done, I'll re-trigger PR checks to verify.

2019-05-15 21:07 UTC, natemcmaster commented
/azp run AspNetCore-helix-test

2019-05-15 21:08 UTC, natemcmaster commented
All Windows.7.Amd64.Open machines should have IIS Express now. Re-running Helix tests to verify.

2019-05-16 00:09 UTC, jkotalik commented
Now getting errors on sqllocaldb. I don't see any error messages either.

```
Executed on a001EDU

C:\dotnetbuild\work\f4958c6b-b3ed-4df3-97ea-823b7bd1fc8f\Work\a40e3bd3-6f53-441e-9eaa-720585794739\Exec>call RunPowershell.cmd mssql\InstallSqlServerLocalDB.ps1   || exit /b 1 
"PS: Running 'C:\dotnetbuild\work\f4958c6b-b3ed-4df3-97ea-823b7bd1fc8f\Work\a40e3bd3-6f53-441e-9eaa-720585794739\Exec\mssql\InstallSqlServerLocalDB.ps1' "
Installing SQL Server 2016 Express LocalDB

Downloading 'SqlLocalDB.msi' to 'C:\dotnetbuild\work\f4958c6b-b3ed-4df3-97ea-823b7bd1fc8f\Work\a40e3bd3-6f53-441e-9eaa-720585794739\Exec\mssql\obj\SqlLocalDB.msi'.

Running 'msiexec /package "C:\dotnetbuild\work\f4958c6b-b3ed-4df3-97ea-823b7bd1fc8f\Work\a40e3bd3-6f53-441e-9eaa-720585794739\Exec\mssql\obj\SqlLocalDB.msi" /NoRestart /Passive IACCEPTSQLLOCALDBLICENSETERMS=YES HIDEPROGRESSBAR=YES'.
```

2019-05-16 00:14 UTC, natemcmaster commented
IISExpress tests for Win7 are running now

> Total tests: 271. Passed: 253. Failed: 0. Skipped: 18.

Didn't expect the SQL Server Local DB. They now pre-install this for us, but I guess our script doesn't no-op well if LocalDB is already installed.

2019-05-16 00:15 UTC, jkotalik approved these changes

2019-05-16 15:58 UTC, merged