Application restarts on changes to Razor files
dotnet/aspnetcore pull request #10716
Opened 2019-05-31 22:22 UTC by pranavkm

* .cshtml and .razor files cause dotnet-watch to reload by default
* .cshtml files do not cause VS or dotnet-watch to reload when using RuntimeCompilation

Fixes https://github.com/aspnet/AspNetCore/issues/9644

2019-05-31 22:55 UTC, rynowak commented on src/Tools/dotnet-watch/src/assets/DotNetWatch.targets
> +        Condition="'%(Content.Extension)' == '.cshtml' AND '$(RazorLangVersion)' >= '3.0'  AND '%(Content.Watch)' != 'false'" />
Why 3.0?

2019-05-31 23:04 UTC, natemcmaster requested changes
I don't like that we're special casing Razor from inside dotnet-watch. The layering feels wrong, especially because this requires also knowing about the version of Razor used. I would prefer to invert the control here and have the Razor SDK instead include this line:
```xml
<ItemGroup>
  <Watch Include="*.razor" />
</ItemGroup>
```

2019-05-31 23:16 UTC, pranavkm commented
> because this requires also knowing about the version of Razor used.

We could remove the version check, I realize that's not necessary. Would that remove the need to put this in the RazorSDK?

2019-05-31 23:34 UTC, natemcmaster commented
It still seems wrong to me that this would put app-model specific information into dotnet-watch. Although dotnet-watch is (currently) owned by our team, it was designed to work in all .NET project types -- test projects, WPF/WinForms, class libraries, console apps, ASP.NE Core, etc. I think project types that want to alter the behavior should use the `<Watch>` item group on their own to suit their needs.

2019-05-31 23:47 UTC, pranavkm commented
Fair enough. I'll get the dotnet-watch specific changes later once I've had a chance to test it.

2019-06-03 10:15 UTC, SteveSandersonMS commented
@pranavkm I don't know what these changes to the NPM project structure are about. Could you explain why there should be this new "utils" package and also "jsutils"?

2019-06-03 11:43 UTC, pranavkm commented
@SteveSandersonMS wrong branch. Fixed it up.

2019-06-03 14:46 UTC, rynowak approved these changes

2019-06-03 14:48 UTC, merged