Master
dotnet/aspnetcore pull request #10822
Opened 2019-06-04 02:00 UTC by wu-yafeng

Log authorization detail failure message by override ToString in each Requirement
 - Add AuthorizationFailure parameter to internal LoggingExtensions.UserAuthorizationFailed
 - Override each Requirement ToString method

Failed Authorization Policy Details in Logs #7789

2019-06-04 16:41 UTC, HaoK commented
@wu-yafeng this looks like a reasonable start, do you think you could add some tests to demonstrate what the log output would look like?

2019-06-05 02:29 UTC, wu-yafeng commented
> @wu-yafeng this looks like a reasonable start, do you think you could add some tests to demonstrate what the log output would look like?

sure

2019-07-11 21:40 UTC, anurse commented
@HaoK 	if we can get this reviewed an in for preview8, awesome. Otherwise it will go to 3.1

2019-07-11 21:50 UTC, HaoK commented on src/Security/Authorization/Core/src/LoggingExtensions.cs
> +                ? "Explicit called fail"
nit: "Fail() was explicitly called."

2019-07-11 21:59 UTC, HaoK commented on src/Security/Authorization/Core/src/LoggingExtensions.cs
> +                : "Following requirement not met " + Environment.NewLine + string.Join(Environment.NewLine, failure.FailedRequirements);
nit: "These requirements were not met:"

2019-07-11 22:00 UTC, HaoK commented on src/Security/Authorization/Core/src/DenyAnonymousAuthorizationRequirement.cs
> +            return $"{nameof(DenyAnonymousAuthorizationRequirement)}:User authenticationted";
type: "User authenticated"?

2019-07-11 22:03 UTC, HaoK commented on src/Security/Authorization/Core/src/AssertionRequirement.cs
> +            return $"{nameof(AssertionRequirement)}:{nameof(Handler)} return {bool.TrueString}";
nit: "{nameof(Handler)} assertion should evaluate to true."

2019-07-11 22:06 UTC, HaoK commented on src/Security/Authorization/Core/src/ClaimsAuthorizationRequirement.cs
> +                : $" AND Claim.Value in ({string.Join("|", AllowedValues)})";
nit: " and Claim.Value is one of the following values: ({string.Join("|", AllowedValues)})"

2019-07-11 22:10 UTC, HaoK requested changes
Looks good except for some minor text changes

2019-07-11 22:46 UTC, wu-yafeng commented
Poor english 😢 ,I'll fix it

2019-10-17 21:22 UTC, anurse commented
@HaoK let's try to close this out now that we're in to the free-for-all 5.0 timeframe ;)

2019-10-25 21:30 UTC, HaoK commented
Thanks @wu-yafeng I had to clean up some minor things and rebased, and merged these changes in PR https://github.com/aspnet/AspNetCore/pull/15350

2019-10-25 21:30 UTC, closed without merging