Release/2.2
dotnet/aspnetcore pull request #11295
Opened 2019-06-17 20:05 UTC by djohnsonUWSA

Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

Addresses #bugnumber (in this specific format)

2019-06-17 20:05 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/aspnet/AspNetCore?pullRequest=11295) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/aspnet/AspNetCore?pullRequest=11295) before we can accept your contribution.<br/><br/>:x: djohnsonUWSA [sign now](https://cla.dotnetfoundation.org/aspnet/AspNetCore?pullRequest=11295)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/aspnet/AspNetCore?pullRequest=11295) it.</sub>

2019-06-17 20:13 UTC, Eilon commented
@djohnsonUWSA was this an accidental PR?

2019-06-18 05:08 UTC, JunTaoLuo requested changes
Hey @djohnsonUWSA, release/2.2 and master are separate branches maintained for different releases and we don't plan to merge one into the other.

2019-06-18 17:01 UTC, Eilon commented
I think this can be closed; it looks accidental.

2019-06-18 17:02 UTC, closed without merging