Endpoint routing in SPA templates
dotnet/aspnetcore pull request #11621
Opened 2019-06-26 21:59 UTC by ryanbrandenburg

Fixes #9108.

2019-06-26 23:34 UTC, rynowak commented on src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Startup.cs
> +            app.UseEndpoints(endpoints =>
This should also change to be similar to the other templates in `ConfigureServices`. This should have `AddControllersWithViews()`, and also `AddRazorPages()` when Identity is present.

2019-06-26 23:35 UTC, rynowak commented on src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Startup.cs
>              app.UseAuthentication();
This should have `UseRouting()` above it, and `UseAuthorization()` after it.

2019-06-26 23:36 UTC, rynowak commented on src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Startup.cs
>              app.UseAuthentication();
With endpoint routing, the auth is handled by middleware now, so the authN/AuthZ middleware sit in between `UseRouting` and `UseEndpoints`

2019-07-01 21:17 UTC, danroth27 requested changes

2019-07-01 21:17 UTC, danroth27 commented on src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Startup.cs
> +            app.UseAuthorization();
I think authorization should only get included when you aren't doing any authentication.

2019-07-01 21:17 UTC, danroth27 commented on src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Startup.cs
> +#if (OrganizationalAuth)
Do we now support org auth with the SPA templates? I didn't think we did...

2019-07-01 21:17 UTC, danroth27 commented on src/ProjectTemplates/Web.Spa.ProjectTemplates/content/React-CSharp/Startup.cs
> +#if (OrganizationalAuth)
Do we now support org auth with the SPA templates? I didn't think we did...

2019-07-01 21:17 UTC, danroth27 commented on src/ProjectTemplates/Web.Spa.ProjectTemplates/content/React-CSharp/Startup.cs
> +            app.UseAuthorization();
I think `UseAuthorization` should only be included when authentication is enabled.

2019-07-01 21:17 UTC, danroth27 commented on src/ProjectTemplates/Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/Startup.cs
> +#if (OrganizationalAuth)
Do we now support org auth with the SPA templates? I didn't think we did...

2019-07-01 21:17 UTC, danroth27 commented on src/ProjectTemplates/Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/Startup.cs
> +            app.UseAuthorization();
Remove if authentication isn't enabled?

2019-07-01 22:17 UTC, ryanbrandenburg commented
:up::date:

2019-07-02 23:15 UTC, danroth27 approved these changes
LGTM

2019-07-03 17:56 UTC, Tratcher commented
What's with all the doc deletions?

2019-07-03 18:24 UTC, ryanbrandenburg commented
Huh, must have happened when I rebased, will fix.

2019-07-03 20:38 UTC, ryanbrandenburg commented
@rynowak better?

2019-07-03 22:32 UTC, ryanbrandenburg commented
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=250430

2019-07-03 22:37 UTC, aspnet-hello commented
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2763

2019-07-09 22:11 UTC, rynowak approved these changes

2019-07-12 17:46 UTC, JunTaoLuo commented
FYI you can ignore the AspNetCore-pr-validation-temp configuration. That shouldn't be running for PRs to master.

2019-07-20 07:21 UTC, merged