Add redirect to domain if request is www.
dotnet/aspnetcore pull request #13486
Opened 2019-08-27 19:07 UTC by SARAVANA1501

Summary of the changes (Less than 80 chars)
 - Added new rule to handle redirects.
 - Added new Extension methods in RewriteOptionsExtensions.cs
 - Added Unit tests to validate the changes.

Addresses #12978 (in this specific format)

2019-08-27 19:34 UTC, SARAVANA1501 commented
Hi Team, 
I found there are few commonalities between Domain redirection vs WWW redirection. Can we stub out common functionalities to base class?
Guide me on this...

2019-08-27 22:28 UTC, Eilon requested changes

2019-08-28 09:40 UTC, SARAVANA1501 commented on src/Middleware/Rewrite/src/RedirectToDomainRule.cs
> +                throw new ArgumentException(nameof(domains));
Hi Eilon,

Changes done, please have a look.

Thanks

2019-08-28 09:40 UTC, SARAVANA1501 commented on src/Middleware/Rewrite/src/RewriteOptionsExtensions.cs
> +        /// Permanently redirects the request to the domain if the request is www.
changes done. please validate.

2019-08-29 16:23 UTC, closed without merging