[Infastructure] Re-enable template tests on master
dotnet/aspnetcore pull request #14101
Opened 2019-09-18 12:07 UTC by javiercn

2019-09-20 18:37 UTC, JunTaoLuo commented on src/ProjectTemplates/test/ProjectTemplates.Tests.csproj
>      <!-- Skip template tests temporarily while we investigate 5.0 migration issues -->
remove this comment

2019-09-20 18:40 UTC, JunTaoLuo reviewed
Should rebase this on https://github.com/aspnet/AspNetCore/pull/14168.

2019-09-20 18:55 UTC, dougbu requested changes
Suggest closing this until I finish the (extra large) merge of the last few weeks' worth of commits from 'release/3.1'. All but two project template tests should be running in 'release/3.1' at the moment.

2019-09-20 19:04 UTC, javiercn commented
> Suggest closing this until I finish the (extra large) merge of the last few weeks' worth of commits from 'release/3.1'. All but two project template tests should be running in 'release/3.1' at the moment.

I'm trying to capture a dump of whatever is causing this to hang. That's why its running. It's bad enough that these tests got disabled in the first place.

2019-09-24 14:58 UTC, javiercn commented
This was done separately.

2019-09-24 14:58 UTC, closed without merging