adds `FallbackTestHtmlAttribute` to `LinkTagHelper`
dotnet/aspnetcore pull request #14105
Opened 2019-09-18 13:22 UTC by XmlmXmlmX

- Adds new attribute to the `LinkTagHelper`.
 - The LinkTagHelper renders the new `FallbackTestHtmlAttribute` to the meta tag.

Addresses #14104

2019-09-18 13:23 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/aspnet/AspNetCore?pullRequest=14105) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/aspnet/AspNetCore?pullRequest=14105) before we can accept your contribution.<br/><br/>:x: XmlmXmlmX [sign now](https://cla.dotnetfoundation.org/aspnet/AspNetCore?pullRequest=14105)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/aspnet/AspNetCore?pullRequest=14105) it.</sub>

2019-09-18 18:11 UTC, mkArtakMSFT commented
Thanks for your PR, @XmlmXmlmX.
@NTaylorMullen can you please review this? Thanks!

2019-10-09 16:37 UTC, pranavkm commented
@XmlmXmlmX you'll need to update the reference assembly for the `TagHelper` project: https://github.com/aspnet/AspNetCore/blob/master/docs/ReferenceAssemblies.md#reference-assemblies. Could you also add some unit tests for this change?

2019-10-09 16:41 UTC, NTaylorMullen requested changes
Should add some tests for this new behavior.

2019-10-09 16:41 UTC, NTaylorMullen commented on src/Mvc/Mvc.TagHelpers/src/LinkTagHelper.cs
> +                .Append(FallbackTestHtmlAttribute)
Add an `if (string.IsNullOrEmpty(FallbackTestHtmlAttribute))` for this bit so we can maintain the ending space `_/>`.

2019-10-09 16:41 UTC, NTaylorMullen commented on src/Mvc/Mvc.TagHelpers/src/LinkTagHelper.cs
> +        public string FallbackTestHtmlAttribute { get; set; }
This needs to be added to the list of valid modes so if you omit `FallbackTestClass` things don't fall over.

2019-10-30 16:26 UTC, closed without merging