Disable ref pack build in 3.0
dotnet/aspnetcore pull request #14746
Opened 2019-10-04 22:55 UTC by wtgodbe

We should disable the build of the ref pack until the reference assembly versions are fixed (see https://github.com/aspnet/AspNetCore/pull/14538)

CC @dougbu @JunTaoLuo @nguerrera

2019-10-04 23:02 UTC, JunTaoLuo approved these changes
Yea I'm still working on some templating test fixes in the linked PR so let's make this change in case I don't get this in by tonight

2019-10-05 04:02 UTC, dougbu approved these changes
Small suggest might get this building&hellip;

2019-10-05 13:18 UTC, Vaseem88 approved these changes

2019-10-06 04:43 UTC, JunTaoLuo commented
FYI you might need to apply the same fix as https://github.com/aspnet/AspNetCore/pull/14538#issuecomment-538640211

2019-10-07 17:08 UTC, wtgodbe commented
> F:\workspace.1\_work\1\s\src\Installers\Windows\Wix.targets(68,5): error MSB3030: Could not copy the file "F:\workspace.1\_work\1\s\artifacts\bin\TargetingPack\x86\Release\AspNetCoreTargetingPack-x86.msi" because it was not found. [F:\workspace.1\_work\1\s\src\Installers\Windows\TargetingPack\TargetingPack.wixproj]

> error : &#x27;&#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;artifacts&#x2F;obj&#x2F;TargetingPack.Layout&#x2F;Release&#x2F;&#x27; directory does not exist [&#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;src&#x2F;Installers&#x2F;Debian&#x2F;TargetingPack&#x2F;Debian.TargetingPack.debproj]‌

And some test failures due to the ref pack not being present:

`PlatformManifestListsAllFiles`
> System.IO.DirectoryNotFoundException : Could not find a part of the path 'F:\\workspace\\_work\\1\\s\\artifacts\\obj\\TargetingPack.Layout\\Release\\packs\\Microsoft.AspNetCore.App.Ref\\3.0.1-ci\\data\\PlatformManifest.txt'.

Plus, all template tests fail because they depend on "restoring" the live-built ref-pack:

> Project new reactredux failed to publish.\r\nProcess exited with code 1\nStdErr: \nStdOut: Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nF:\\workspace\\_work\\1\\s\\src\\ProjectTemplates\\test\\bin\\Release\\netcoreapp3.0\\TestTemplates\\AspNet.reactredux.okac0s5wov4\\AspNet.reactredux.okac0s5wov4.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 3.0.1-ci)

Would it make more sense to disable _publishing_ the ref pack, rather than disabling building it?

2019-10-07 17:25 UTC, JunTaoLuo commented
Ideally it would make sense for us to not build the 3.0 ref packs and not refer to them in any way in tests. However, given the time crunch, it might make sense to build but not publish them. However, we should double check and make sure that the logic to refer to the 3.0.1-ci ref packs in our template tests is custom and users won't see this when using the official 3.0.1 bits when released.

2019-10-07 17:27 UTC, dougbu commented
> Would it make more sense to disable publishing the ref pack, rather than disabling building it?

1. The ref pack and targeting pack tests should also be disabled when not building the tested projects. Or, they should test the version of the packs specified in the baseline files.
2. The templates should resolve the baseline version when the packs aren't being built. This likely means using the baseline version when `$(IsTargetingPackBuilding)` is `false`. Change would be in the ref and runtime projects because they are queried to get the right (often distinct) versions.

2019-10-07 19:02 UTC, JunTaoLuo commented
FYI @wtgodbe we need to update the logic at https://github.com/aspnet/AspNetCore/blob/release/3.0/eng/Versions.props#L29-L34. The baselines have been updated and this is a servicing branch now.

2019-10-07 23:06 UTC, wtgodbe commented
Testing a few fixes while I work out the best way to calculate the correct package version for the RefPack in the template tests

2019-10-08 00:37 UTC, JunTaoLuo commented
@wtgodbe you'll probably need my fix at https://github.com/aspnet/AspNetCore/pull/14538/commits/87f753a2e84180d6dacded89e3a4e3becec81589. nuget.exe pack doesn't use the <NuspecProperty> trick. I suppose I could have removed the ItemGroup as a cleanup though.

2019-10-08 00:59 UTC, dougbu requested changes
1. Merge for 3.0.2 and not 3.0.1
2. Up to you whether you fix `IsServicingBuild` (set `DisableServicingFeatures` to `false`) in this PR or we do that completely separately. If included, must remove PatchConfig.props and references to that file. The targeting packs and related installers are the _only_ items not usually built in servicing builds for 3.0 and later.

2019-10-08 00:59 UTC, dougbu commented on src/Framework/test/TargetingPackTests.cs
> +        [Skip]
```suggestion
        [Fact(Skip="link to an issue")]
```

2019-10-08 00:59 UTC, dougbu commented on src/Installers/Debian/Directory.Build.targets
> +      Condition="'$(IsTargetingPackBuilding)' != 'false'"
Likely minor but could put this `Condition` on the `DebBuild` target

2019-10-14 18:23 UTC, merged