Keep Blazor at pre-release for 3.1
dotnet/aspnetcore pull request #16829
Opened 2019-11-04 21:46 UTC by JunTaoLuo

This ensures that the following Blazor packages remain branded as 3.1.x-preview4:
•	Microsoft.AspNetCore.Blazor
•	Microsoft.AspNetCore.Blazor.HttpClient
•	Microsoft.AspNetCore.Blazor.DataAnnotations.Validation
•	Microsoft.AspNetCore.Blazor.Templates
•	Microsoft.AspNetCore.Blazor.Build
•	Microsoft.AspNetCore.Blazor.Mono
•	Microsoft.AspNetCore.Blazor.Server
•	Microsoft.AspNetCore.Blazor.DevServer

Note that Microsoft.AspNetCore.Blazor.Mono is built in aspnet/Blazor so that will require a different branding change.

2019-11-04 22:46 UTC, dougbu requested changes

2019-11-04 22:46 UTC, dougbu commented on eng/Versions.props
> +    <BlazorClientPreReleasePreviewNumber>4</BlazorClientPreReleasePreviewNumber>
```suggestion
    <BlazorClientPreReleasePreviewNumber>3</BlazorClientPreReleasePreviewNumber>
```
Don't jump _ahead_ of `$(PreReleasePreviewNumber)`. We can change this when stabilizing versions and removing the other property.

2019-11-05 00:11 UTC, JunTaoLuo commented
Yea this shouldn't be merged until we have branding updates for GA.

2019-11-08 17:29 UTC, wtgodbe commented
I'll merge this when I update branding to stable Sunday/Monday

2019-11-11 20:35 UTC, JunTaoLuo commented
@wtgodbe are these ready to go in yet?

2019-11-13 04:51 UTC, merged