Adding some guidance regarding using StackOverflow in the issue template
dotnet/aspnetcore pull request #17306
Opened 2019-11-21 18:34 UTC by mkArtakMSFT

Also, I've moved the `security-related comment into the comments section, as it doesn't make sense for that text to show up in already-filed issue.

2019-11-21 18:37 UTC, blowdart requested changes

2019-11-21 18:37 UTC, blowdart commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If you believe you have an issue that affects the SECURITY of the platform, please do NOT create an issue and instead email your issue details to secure@microsoft.com. Your report may be eligible for
New URL :) https://www.microsoft.com/en-us/msrc/bounty-dot-net-core

2019-11-21 18:40 UTC, javiercn approved these changes

2019-11-21 19:04 UTC, blowdart approved these changes

2019-11-21 20:36 UTC, danroth27 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +For other type of questions, consider using the [StackOverflow](https://stackoverflow.com) forum.
```suggestion
For other types of questions, consider using [StackOverflow](https://stackoverflow.com).
```

2019-11-21 21:20 UTC, analogrelay approved these changes

2019-11-21 21:33 UTC, mkArtakMSFT commented
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=434605

2019-11-21 21:37 UTC, aspnet-hello commented
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2859

2019-11-22 00:55 UTC, Pilchie approved these changes

2019-11-22 17:00 UTC, merged