Add an extension method Users to IHubClients witch takes IEnumerable parameter
dotnet/aspnetcore pull request #17360
Opened 2019-11-23 22:12 UTC by Marusyk

Add a simple extension method toIHubClients witch takes IEnumerable parameter

Addresses #17285

Please review
Thank you in advance

2019-11-25 17:20 UTC, anurse commented
We should add this to all the client methods if we're going to do it (Groups, GroupsExcept, etc. etc. etc.). Also, we need to discuss if an extension method is right or if we should use a Default Interface Member. The latter would allow an implementation to override it and provide different logic for `IEnumerable` over `IReadOnlyList`.

Thoughts on this @davidfowl @halter73 @BrennanConroy ?

2019-11-25 18:16 UTC, halter73 commented
I agree we should do the same for Groups, GroupsExcept, etc... I think for something as trivial as this, and extension method is still appropriate. I don't know why an interface implementor would want to do anything special for `IEnumerable` vs `IReadOnlyList`

2019-12-04 14:06 UTC, Marusyk commented
Can anybody suggest how to fix build and what is Pull Request Labeler?

2019-12-04 19:35 UTC, halter73 commented
> Can anybody suggest how to fix build and what is Pull Request Labeler?

https://github.com/aspnet/AspNetCore/blob/master/docs/ReferenceAssemblies.md#when-changing-public-api

@aspnet/asp-net-api-reviews We'll want to do an API review on this before merging.

I wouldn't worry about the PR labeler. That doesn't block the build. I don't even think it's supposed to run for external PRs (https://github.com/aspnet/AspNetCore/pull/15171) @mkArtakMSFT Do you know what's going on here?

2019-12-04 22:19 UTC, Marusyk commented
Thanks,

I cann't build localy because https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#common-error-unable-to-locate-the-net-core-sdk

2019-12-06 19:13 UTC, anurse commented
> I can't build locally because [/docs/BuildFromSource.md@`master`#common-error-unable-to-locate-the-net-core-sdk](https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#common-error-unable-to-locate-the-net-core-sdk) [](/aspnet/AspNetCore/blob/HEAD@{2019-12-04T22:19:23Z}/docs/BuildFromSource.md#common-error-unable-to-locate-the-net-core-sdk)

Have you enabled the "Use previews of the .NET Core SDK" checkbox as suggested in that doc?

Even if you can't fully build, you may still be able to run the script @halter73 mentioned to update the ref assembly. Updating that is necessary to resolve the Code Check failure.

2019-12-07 17:36 UTC, Marusyk commented
@anurse yes, I have enabled the "Use previews of the .NET Core SDK" checkbox as suggested in that doc

2019-12-11 20:17 UTC, anurse commented
Excellent! Thanks!

A note here about the process from here:

1. Someone from the team needs to review this and sign off (ping @halter73 @BrennanConroy  ;)).

1. We'll review the new API in our regular API review meeting (we do this for all public API changes in mature areas like SignalR) and either approve it or provide further feedback.

Once we've got those done, we'll merge it in!

2019-12-11 22:45 UTC, BrennanConroy requested changes

2019-12-11 22:45 UTC, BrennanConroy commented on src/SignalR/server/Core/src/HubClientsExtensions.cs
> +        public static T GroupExcept<T>(this IHubClients<T> hubClients, IEnumerable<string> excludedConnectionIds)
This is missing the group name

2019-12-11 23:33 UTC, BrennanConroy approved these changes

2019-12-12 00:22 UTC, halter73 approved these changes

2019-12-16 18:35 UTC, pranavkm reviewed
We want to make sure this isn't a source breaking change

2019-12-16 21:49 UTC, rynowak commented
> 
> 
> We want to make sure this isn't a source breaking change

Specifically we should make sure that using array or list here doesn't lead to an ambiguity compiler diagnostic.

2019-12-18 22:41 UTC, halter73 commented
I tried this with an Array, List and IEnumerable (which was really an Array stored as an IEnumerable). Since both Array and List implement IReadOnlyList and IReadOnlyList inherits from IEnumerable, the compiler chooses the more-derived IReadOnlyList overload. In the IEnumerable case, the compiler chooses the IEnumerable extension method since that's the only workable overload.

Overload selection is a compile-time decision, so an Array/List/whatever can still be passed to the IEnumerable extension method if the compiler only knows it's an IEnumerable, but I don't see a problem with that.

2019-12-18 22:41 UTC, merged

2019-12-18 22:41 UTC, halter73 commented
Thanks @Marusyk.