Add nullable annotations to Http.Abstractions, Http.Features, Connections.Abstractions
dotnet/aspnetcore pull request #18084
Opened 2020-01-02 09:06 UTC by JamesNK

Addresses https://github.com/aspnet/AspNetCore/issues/5680

Annotations on projects at the bottom of the dependency tree. Because I haven't converted the tests there may be some types that are not null but should be. Should discover those as more projects are annotated.

2020-01-02 19:54 UTC, halter73 commented on src/Http/Headers/src/BaseHeaderParser.cs
> +        public sealed override bool TryParseValue(StringSegment value, ref int index, [MaybeNullWhen(false)]out T parsedValue)
It looks like TryParseValue can return true even in cases where parsedValue is never set if SupportsMultipleValues is also true.

2020-01-02 20:01 UTC, halter73 commented on src/Http/Headers/src/HttpHeaderParser.cs
> +        public abstract bool TryParseValue(StringSegment value, ref int index, [NotNullWhen(true)]out T parsedValue);
Shouldn't the type be marked nullable when using attributes like NotNullWhen?

2020-01-02 21:09 UTC, Tratcher requested changes
How do you plan to handle microsoft.extensions.activatorutilities.sources?

2020-01-07 00:01 UTC, rynowak commented
API review YO

2020-02-19 21:25 UTC, anurse commented
Sounds like there are some build issues with using nullable annotations here. @JamesNK you can check in with @dotnet/aspnet-build and see if we can figure this out?

2020-02-19 21:27 UTC, wtgodbe commented
/azp run

2020-02-20 00:34 UTC, dougbu commented
>  Sounds like there are some build issues with using nullable annotations here.

@anurse something beyond the missing `Contract.Requires(...)` calls that @Tratcher mentioned? Could you be a bit more specific?

2020-02-20 17:45 UTC, anurse commented
Just what @JamesNK said in Triage ;).

2020-02-24 22:33 UTC, closed without merging

2020-02-24 22:34 UTC, JamesNK commented
No immediate plans to look at this. Can re-open when I have time in the future.