Use 3.1.1 versions in blazor-wasm
dotnet/aspnetcore pull request #18521
Opened 2020-01-22 22:27 UTC by pranavkm

2020-01-22 22:40 UTC, dougbu approved these changes
If this passes validation builds, great. Otherwise, please close this PR and add your commit to #18280. That baseline update will do the needful to ensure this works.

2020-01-22 22:41 UTC, pranavkm commented
Thanks @dougbu. We're using this as a fallback in case the other PR needs further time to stabilize.

2020-01-22 22:42 UTC, javiercn approved these changes
Provided build passes

2020-01-22 22:42 UTC, wtgodbe commented
I probably won't get my PR instead, so if this works as expected, let's take this for preview1. Please crack open some binaries & nupkgs from this to make sure that they're referencing 3.1.1 packages & 3.1.0.0 AssemblyVersions

2020-01-22 23:13 UTC, pranavkm commented
> [ERROR] A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'F:\workspace\_work\1\s\.dotnet\shared\Microsoft.AspNetCore.App\3.1.1'.

Might need a little more work to get going.

2020-01-23 00:14 UTC, wtgodbe commented
I tried updating to the 3.1.1 SDK

2020-01-23 18:01 UTC, wtgodbe commented
What's up with the E2E tests? The build says they failed, but AzDO lists them under "other" with no logs. E.g. `Render_HtmlBlock_Integration`

2020-01-23 18:05 UTC, wtgodbe commented
At a glance, the packages/assemblies look good. `Microsoft.AspNetCore.Blazor` depends on the 3.1.1 versions of `Microsoft.AspNetCore.Components.Web` and `Microsoft.Extensions.Configuration`, and the 3.2.0-preview1 version of `Mono.WebAssembly.Interop`. However, the assembly in the package appears to be referencing ref assemblies from AspNetCore, but implementation assemblies from Extensions (e.g. Microsoft.Extensions.DependencyInjection.Abstractions version 3.1.1.0) - There's likely some work we did in 3.1 that didn't make it into this branch (CC @dougbu, @JunTaoLuo, @Pilchie)

2020-01-23 19:04 UTC, ryanbrandenburg requested changes

2020-01-23 19:04 UTC, ryanbrandenburg commented on src/ProjectTemplates/test/BlazorWasmTemplateTest.cs
> +            // await BuildAndRunTest(project.ProjectName, project);
This is effectively the same thing as disabling the test, all of the interesting things happen in BuildAndRunTests and TestBasicNavigation. If we MUST do this for some reason at least file an issue about re-instating it.

2020-01-23 20:13 UTC, JunTaoLuo commented
@wtgodbe maybe the changes are stuck in https://github.com/dotnet/aspnetcore/pull/17873

2020-01-23 22:23 UTC, pranavkm commented
I spent a couple of iterations trying to resolve this, but it seems fairly non-trivial. In particular edges where we reference implementation assemblies (transitively via Blazor's reference to AspNetCore) and reference assemblies result in a gnarly mess of version conflicts. I wonder if we should just remove project references from the equation in the blazor branch and instead reference packages for things that are already shipped. As it is, version updates are manual in the 3.1 branch. It might be a less complicated way to go about it.

2020-01-23 22:23 UTC, closed without merging