Added Log events for Httpsys
dotnet/aspnetcore pull request #18551
Opened 2020-01-24 05:05 UTC by kuns200

Added Log events for Httpsys
Also, Added event which were evented as 0.

Addresses #6381(in this specific format)

2020-01-24 05:06 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=18551) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=18551) before we can accept your contribution.<br/><br/>:x: kuns200 [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=18551)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=18551) it.</sub>

2020-01-24 09:02 UTC, Kahbazi commented on src/Servers/HttpSys/src/LoggerEventIds.cs
> +        public static EventId TokenDisconnectTriggered = new EventId(13, "TokenDisconnectTriggered");
There are duplicate events for event id 13, 14 and 1.

2020-01-27 18:46 UTC, Tratcher requested changes

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/MessagePump.cs
> +                        _logger.LogInformation(LoggerEventIds.RequestCancelled, "Canceled, terminating " + _outstandingRequests + " request(s).");
```suggestion
                        _logger.LogInformation(LoggerEventIds.StopCancelled, "Canceled, terminating " + _outstandingRequests + " request(s).");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/NativeInterop/UrlGroup.cs
> +            _logger.LogDebug(LoggerEventIds.PrefixListened, "Listening on prefix: {0} " , uriPrefix);
```suggestion
            _logger.LogDebug(LoggerEventIds.RegisteringPrefix, "Listening on prefix: {0} " , uriPrefix);
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/NativeInterop/UrlGroup.cs
> +            _logger.LogInformation(LoggerEventIds.PrefixListenStopped, "Stop listening on prefix: {0} " , uriPrefix);
```suggestion
            _logger.LogInformation(LoggerEventIds.UnregisteringPrefix, "Stop listening on prefix: {0} " , uriPrefix);
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/NativeInterop/UrlGroup.cs
> +                _logger.LogError(LoggerEventIds.V2ConfigCleanupFailed, "CleanupV2Config; Result: {0}" , statusCode);
```suggestion
                _logger.LogError(LoggerEventIds.CloseUrlGroupError, "HttpCloseUrlGroup; Result: {0}" , statusCode);
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/Request.cs
> +                        RequestContext.Logger.LogDebug(LoggerEventIds.CryptoException, ce, "An error occurred reading the client certificate.");
```suggestion
                        RequestContext.Logger.LogDebug(LoggerEventIds.ErrorInReadingCertificate, ce, "An error occurred reading the client certificate.");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs
> +            Logger.LogInformation(LoggerEventIds.ChannelBindingRetrived,"Channel binding retrieved.");
```suggestion
            Logger.LogDebug(LoggerEventIds.ChannelBindingRetrived,"Channel binding retrieved.");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs
> +                    Logger.LogError(LoggerEventIds.WriteFlushed, exception, "Flush");
```suggestion
                    Logger.LogError(LoggerEventIds.WriteError, exception, "Flush");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs
> +                    Logger.LogDebug(LoggerEventIds.WriteFlushedIgnored, $"Flush; Ignored write exception: {statusCode}");
```suggestion
                    Logger.LogDebug(LoggerEventIds.WriteErrorIgnored, $"Flush; Ignored write exception: {statusCode}");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs
> +                    Logger.LogDebug(LoggerEventIds.AbortButDonotClose,$"FlushAsync; Ignored write exception: {statusCode}");
```suggestion
                    Logger.LogDebug(LoggerEventIds.WriteErrorIgnored,$"FlushAsync; Ignored write exception: {statusCode}");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs
> +                    Logger.LogDebug(LoggerEventIds.FileSendAsyncAbortButDonotClose,$"SendFileAsync; Ignored write exception: {statusCode}");
```suggestion
                    Logger.LogDebug(LoggerEventIds.FileSendAsyncErrorIgnored,$"SendFileAsync; Ignored write exception: {statusCode}");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/ResponseStreamAsyncResult.cs
> +                        logger.LogDebug(LoggerEventIds.IOCompletedCancelled,$"FlushAsync.IOCompleted; Write cancelled with error code: {errorCode}");
```suggestion
                        logger.LogDebug(LoggerEventIds.WriteCancelled,$"FlushAsync.IOCompleted; Write cancelled with error code: {errorCode}");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/ResponseStreamAsyncResult.cs
> +                        logger.LogError(LoggerEventIds.IOCompletedCancelled, exception, "FlushAsync.IOCompleted");
```suggestion
                        logger.LogError(LoggerEventIds.WriteError, exception, "FlushAsync.IOCompleted");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/ResponseStreamAsyncResult.cs
> +                        logger.LogDebug(LoggerEventIds.IOCompletedFailQuiet, $"FlushAsync.IOCompleted; Ignored write exception: {errorCode}");
```suggestion
                        logger.LogDebug(LoggerEventIds.WriteErrorIgnored, $"FlushAsync.IOCompleted; Ignored write exception: {errorCode}");
```

2020-01-27 18:46 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/ResponseStreamAsyncResult.cs
> +                logger.LogError(LoggerEventIds.IOCompletedFailed, e, "FlushAsync.IOCompleted");
```suggestion
                logger.LogError(LoggerEventIds.WriteError, e, "FlushAsync.IOCompleted");
```

2020-01-28 05:08 UTC, kuns200 commented
i will fix them. thanks for your comments.

2020-01-29 05:09 UTC, kuns200 commented
fix in progress.

2020-01-29 18:59 UTC, Tratcher requested changes
Much better. One more pass to make the names more consistent and you should be done.

2020-01-29 18:59 UTC, Tratcher commented on src/Servers/HttpSys/src/HttpSysListener.cs
> +                    Logger.LogError(LoggerEventIds.ListenerStartException, exception, "Start");
Be consistent about Error vs Exception vs Failed/Failure. Let's use Error as it's simpler.

2020-01-29 18:59 UTC, Tratcher commented on src/Servers/HttpSys/src/HttpSysListener.cs
> +                    Logger.LogError(LoggerEventIds.ErrorInDispose, exception, "Dispose");
Also consistent ordering?
```suggestion
                    Logger.LogError(LoggerEventIds.ListenerDisposeError, exception, "Dispose");
```

2020-01-29 18:59 UTC, Tratcher commented on src/Servers/HttpSys/src/NativeInterop/UrlGroup.cs
> +            _logger.LogDebug(LoggerEventIds.RegisteringPrefix, "Listening on prefix: {0} " , uriPrefix);
Good formatting improvement.
```suggestion
            _logger.LogDebug(LoggerEventIds.RegisteringPrefix, "Listening on prefix: {0}" , uriPrefix);
```

2020-01-29 18:59 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs
> +                    Logger.LogError(LoggerEventIds.LessBytesThenExpected, "ResponseStream::Dispose; Fewer bytes were written than were specified in the Content-Length.");
```suggestion
                    Logger.LogError(LoggerEventIds.FewerBytesThanExpected, "ResponseStream::Dispose; Fewer bytes were written than were specified in the Content-Length.");
```

2020-01-30 17:32 UTC, kuns200 commented on src/Servers/HttpSys/src/HttpSysListener.cs
> +                    Logger.LogError(LoggerEventIds.ErrorInDispose, exception, "Dispose");
made all events to look as Error.

2020-01-31 05:55 UTC, Tratcher commented
Please move your Kestrel change to it's own branch and pull request. It's easier to review and merge distinct features.

2020-02-04 18:21 UTC, Tratcher approved these changes

2020-02-04 18:21 UTC, Tratcher commented on src/Servers/HttpSys/src/LoggerEventIds.cs
> +
Remove extra lines
```suggestion
```

2020-02-04 23:43 UTC, Tratcher commented on src/Servers/HttpSys/src/LoggerEventIds.cs
> +
```suggestion
```

2020-02-04 23:43 UTC, Tratcher commented on src/Servers/HttpSys/src/LoggerEventIds.cs
> +
```suggestion
```

2020-02-04 23:44 UTC, Tratcher commented on src/Servers/HttpSys/src/LoggerEventIds.cs
> +
```suggestion
```

2020-02-05 18:54 UTC, merged

2020-02-05 18:54 UTC, Tratcher commented
Thanks