Update XML docs for OnStarting
dotnet/aspnetcore pull request #19534
Opened 2020-03-03 18:20 UTC by anurse

Fixes https://github.com/dotnet/aspnetcore/issues/19530

I have both a brief `<summary>` update (because that shows in IntelliSense) and detailed justification in `<remarks>`.

2020-03-03 18:22 UTC, Tratcher approved these changes

2020-03-03 19:18 UTC, Rick-Anderson requested changes
Per MS style guide:

* Avoid future tense. Future tense is not banned, but when not needed avoid it.
* Avoid parenthetical clauses. Again, not banned.

2020-03-03 19:18 UTC, Rick-Anderson commented on src/Http/Http.Abstractions/src/HttpResponse.cs
> +        /// first).
```suggestion
        /// Callbacks registered here run in reverse order.
        /// </summary>
        /// <remarks>
        /// Callbacks registered here run in reverse order. The last one registered is invoked first.
        /// The reverse order is done to replicate the way middleware works, with the inner-most middleware looking at the
        /// response first).
```

2020-03-03 19:18 UTC, Rick-Anderson commented on src/Http/Http.Abstractions/src/HttpResponse.cs
> +        /// </remarks>
```suggestion
        /// Callbacks registered here run in reverse order.
        /// </summary>
        /// <remarks>
        /// Callbacks registered here run in reverse order. The last one registered is invoked first.
        /// The reverse order is done to replicate the way middleware works, with the inner-most middleware looking at the
        /// response first).
```

2020-03-03 22:14 UTC, anurse commented
Thanks @Rick-Anderson !

2020-03-04 16:27 UTC, anurse commented on src/Http/Http.Abstractions/src/HttpResponse.cs
> +        /// response first.
```suggestion
        /// response first.
        /// </remarks>
```

2020-03-04 19:35 UTC, anurse commented
Rebased

2020-03-18 20:58 UTC, merged