Add issue template with list of repos
dotnet/aspnetcore pull request #1971
Opened 2017-03-15 16:56 UTC by natemcmaster

We get lots of noise here, but no one is really following up on issues. This message will appear in the issue box when users try to make a new issue. Hopefully this will help them find the right place to file issues.

2017-03-15 16:56 UTC, dnfclas commented
@natemcmaster,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-03-15 22:49 UTC, Eilon requested changes

2017-03-15 22:49 UTC, Eilon commented on .github/ISSUE_TEMPLATE.md
> +Common ASP.NET repos and projects:
... and Entity Framework!

2017-03-15 22:49 UTC, Eilon commented on .github/ISSUE_TEMPLATE.md
> +Common projects that are not ASP.NET:
I'd just say "Other common projects"?

2017-03-15 22:49 UTC, Eilon commented on .github/ISSUE_TEMPLATE.md
> + - .NET Core CLI, SDK, or runtime: https://github.com/dotnet/core
Is that repo for all of those projects? CLI is in https://github.com/dotnet/cli, no?

2017-03-15 22:53 UTC, natemcmaster commented on .github/ISSUE_TEMPLATE.md
> + - .NET Core CLI, SDK, or runtime: https://github.com/dotnet/core
dotnet/core is the .NET Core "Home" repo. It contains a list of relevant repos including dotnet/cli, dotnet/sdk, and others.

2017-03-16 03:31 UTC, Eilon approved these changes

2017-03-16 03:31 UTC, Eilon commented on .github/ISSUE_TEMPLATE.md
> + - and more! See a full list here: https://github.com/aspnet
Nice 😄

2017-03-16 03:33 UTC, Eilon requested changes

2017-03-16 03:33 UTC, Eilon commented on .github/ISSUE_TEMPLATE.md
> +This repo is not closely monitored by product and development teams.
Oh actually wait, one more thing. The point isn't about whether it's monitored or not, but rather about how to get issues resolved most quickly. I think this text might represent that better:

> To address your issues more quickly, please open the issue in the most appropriate repository. These are some of the most common repos:

2017-03-16 04:33 UTC, natemcmaster commented on .github/ISSUE_TEMPLATE.md
> +This repo is not closely monitored by product and development teams.
updated

2017-03-16 16:29 UTC, Eilon approved these changes
:shipit: 😄

2017-03-16 16:33 UTC, merged