Better retries
dotnet/aspnetcore pull request #22898
Opened 2020-06-12 22:08 UTC by HaoK

- dotnet-install.ps1 retry logic copied from eng/common/tools.ps1

2020-06-13 02:49 UTC, Pilchie commented
:eyes:

2020-06-16 09:12 UTC, HaoK commented
Gist of the change is added a new download.ps1 helper that does 5 retries with exponential backoff (copied from eng/common/tools.ps1), everywhere we were using invoke-webrequest directly has been updated to use this

2020-06-16 21:13 UTC, dougbu requested changes
This covers the `*.ps1` files nicely.

We also need to add `--retries 5` to all `curl` commands in `*.sh` files. Are you planning to do that in a separate PR❔

2020-06-16 21:44 UTC, HaoK commented on eng/helix/content/dotnet-install.ps1
> +#
Oops yeah, I just was running things locally to make sure it worked, didn't notice it left a copy, good catch

2020-06-16 21:45 UTC, HaoK commented on eng/scripts/Download.ps1
> + <#
I'll file an issue for this as there are small differences in the scripts sometimes

2020-06-16 21:46 UTC, HaoK commented
Yeah I'll do the non ps1's in a different PR

2020-06-16 21:55 UTC, HaoK commented on eng/scripts/Download.ps1
> + <#
https://github.com/dotnet/aspnetcore/issues/23021

2020-06-16 22:17 UTC, HaoK commented on eng/helix/content/InstallDotNet.ps1
> +Invoke-Expression "& $PSScriptRoot\dotnet-install.ps1 -Architecture $arch -Runtime dotnet -Version $runtimeVersion -InstallDir $installDir"
Are you referring to https://github.com/dotnet/aspnetcore/blob/1ab62e80380971a06dd1315a2b9b60c260305ea6/eng/common/tools.ps1#L264 ?  That looks like its only trying again if its a runtime install and it tries with the private feeds, I ran into this weirdness too, but the common scripts aren't running installs twice on all failures, I don't think we should mimic this logic.  If dotnet-install.sh fails, that seems like a legit failure and not something we should retry

2020-06-16 23:05 UTC, dougbu requested changes
One thing to test and maybe fix. Otherwise, looks great!

2020-06-16 23:05 UTC, dougbu commented on eng/helix/content/Download.ps1
> +      Write-Warning $_.Exception.Message -ErrorAction Continue
Have you tested to be sure `$_.Exception` is available outside the `catch`❔ I doubt it is. Might need to copy the message into a variable within the `catch` block.

2020-06-16 23:05 UTC, dougbu approved these changes
Ooops

2020-06-17 06:17 UTC, merged