Obsolete MigrationsEndpointMiddleware
dotnet/aspnetcore pull request #23645
Opened 2020-07-02 22:59 UTC by JunTaoLuo

Following up our offline discussion where we decided to remove MigrationsEndpointMiddleware. Note that I added the RazorPageGenerator (originally from aspnetcore-tooling) since we need that to generate the Designer.cs file.

2020-07-02 23:18 UTC, Tratcher requested changes

2020-07-02 23:18 UTC, Tratcher commented on src/Middleware/Diagnostics.EntityFrameworkCore/src/DatabaseErrorPageMiddleware.cs
>          public DatabaseErrorPageMiddleware(
Make a new overload that doesn't have the obsolete parameter.

2020-07-02 23:18 UTC, Tratcher commented on src/Middleware/Diagnostics.EntityFrameworkCore/src/Views/DatabaseErrorPageModel.cs
> +        [Obsolete("This is obsolete and will be removed in a future version.")]
This class is internal, you can just remove this overload and the property.

2020-07-02 23:18 UTC, Tratcher commented on src/Middleware/Diagnostics.EntityFrameworkCore/test/UnitTests/DatabaseErrorPageOptionsTest.cs
>              var options = new DatabaseErrorPageOptions();
Remove this whole test class.

2020-07-02 23:18 UTC, Tratcher commented on src/Middleware/Diagnostics.EntityFrameworkCore/src/MigrationsEndPointMiddleware.cs
>      public class MigrationsEndPointMiddleware
This is dead code now. Remove all internal content and make the public APIs throw NotImplementedException.

2020-07-06 18:11 UTC, Tratcher approved these changes

2020-07-30 22:27 UTC, JunTaoLuo commented
Closing this since we are taking a different approach to this issue.

2020-07-30 22:27 UTC, closed without merging