Fix uppercase and lowercase check to be unicode instead of ascii
dotnet/aspnetcore pull request #23668
Opened 2020-07-04 06:50 UTC by Youssef1313

Fixes #23562

2020-07-04 07:33 UTC, Kahbazi commented
Does this message also need to be updated?
https://github.com/dotnet/aspnetcore/blob/c7a2c0648a0fad7dc1f98c18702d1a4c1d72bcc2/src/Identity/Extensions.Core/src/Resources.resx#L193

2020-07-04 07:39 UTC, Youssef1313 commented
@Kahbazi Yes. Thanks. I'll update it.

2020-07-04 07:51 UTC, Kahbazi commented
I think this test needs to be updated too.
https://github.com/dotnet/aspnetcore/blob/c95ee2b051814b787b07f55ff224d03d550aafeb/src/Identity/test/Identity.Test/PasswordValidatorTest.cs#L149

2020-07-04 09:23 UTC, Youssef1313 commented
@Kahbazi Thanks again for review. I've updated the error message in the test, and also added a test case with the new behavior.

2020-07-04 09:24 UTC, Youssef1313 commented
Any idea if there is any specific file that should be updated in this PR to track the breaking change?

2020-07-04 09:37 UTC, Kahbazi commented
I also find this type that need to be updated.
https://github.com/dotnet/aspnetcore/blob/c95ee2b051814b787b07f55ff224d03d550aafeb/src/Identity/src/Core/PasswordOptions.cs#L28

2020-07-06 16:52 UTC, HaoK commented
I think its probably best to take a compromise approach, seems fine to change the default implementation and comments to use Unicode Upper/Lower, but I think there's no harm in leaving these virtual, and let people continue to override the behavior to implement Upper/Lower as they see fit.

2020-07-06 16:55 UTC, HaoK requested changes
Revert the virtual changes and I think this looks reasonable

2020-07-06 17:10 UTC, Youssef1313 commented
@HaoK, I've added virtual back. Do you want me to use `Rune` instead of char.IsUpper and char.IsLower?

2020-07-06 17:21 UTC, HaoK commented
Yeah if @GrabYourPitchforks suggests using Rune, I think we should listen to his guidance on correctness there :)

2020-07-06 17:36 UTC, Youssef1313 commented on src/Identity/Extensions.Core/src/PasswordValidator.cs
>          }
I'm unsure if I implemented it correctly. Mentioning @GrabYourPitchforks for review.

2020-07-06 17:39 UTC, Youssef1313 commented on src/Identity/Extensions.Core/src/PasswordValidator.cs
>          }
I'm unsure if I implemented it correctly. Mentioning @GrabYourPitchforks for review.

2020-07-06 19:14 UTC, GrabYourPitchforks commented
The suggestion was that the methods `IsLower(char)` and `IsUpper(char)` weren't correct in the first place and that we should no longer use these methods. The issue https://github.com/dotnet/aspnetcore/issues/23562 still needs to be fleshed out, including exactly what problem it's trying to solve. The issue as reported concerns itself only with German characters, but is it really indicating a larger issue that also affects our Chinese and Japanese and Korean users? That really deserves a more thorough discussion. I think this PR, while well-intentioned, is premature until a plan of action has been settled on there.

2020-07-15 22:11 UTC, blowdart commented
Thank you for this, but it's too big a beaking risk for now.

2020-07-15 22:11 UTC, closed without merging