Fix various minor spelling mistakes
dotnet/aspnetcore pull request #24019
Opened 2020-07-16 16:24 UTC by adrianwright109

Fixes minor spelling mistakes in Components area.

2020-07-16 16:27 UTC, javiercn approved these changes

2020-07-16 16:32 UTC, SteveSandersonMS commented on src/Components/Components/test/ParameterViewTest.Assignment.cs
> +        public void IncomingParameterMatchesOverriddenParameter_ThatDoesNotHasAttribute()
```suggestion
        public void IncomingParameterMatchesOverriddenParameter_ThatDoesNotHaveAttribute()
```

2020-07-16 20:23 UTC, pranavkm requested changes
@adrianwright109 could you undo changes to the submodule?

2020-07-16 21:27 UTC, adrianwright109 commented
Changes to submodule have been undone.

2020-07-16 23:37 UTC, captainsafia approved these changes
Coolio! Thanks for submitting this contribution and addressing the follow-ups.

2020-07-17 00:05 UTC, captainsafia commented
@pranavkm Can you re-review you this? Your review is blocking the merge.

2020-07-17 00:24 UTC, pranavkm approved these changes

2020-07-17 00:24 UTC, merged

2020-07-17 00:24 UTC, pranavkm commented
Thanks for the PR!