Throw BadHttpRequestException in HttpSys
dotnet/aspnetcore pull request #24213
Opened 2020-07-22 18:56 UTC by Kahbazi

Fixes https://github.com/dotnet/aspnetcore/issues/20688

2020-07-22 19:05 UTC, halter73 approved these changes
LGTM. It better matches Kestrel's and IIS in-proc's behavior.

2020-07-22 19:11 UTC, Tratcher requested changes
This only covers half of #20688 so far. The other half is to catch the exception and return that status code. That would probobly happen here: https://github.com/dotnet/aspnetcore/blob/e9d989f758297c8d1de0c06ce07db3620ae7d451/src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs#L274-L292

2020-07-22 19:11 UTC, Tratcher commented on src/Servers/HttpSys/src/RequestProcessing/RequestStream.cs
> +                    throw new BadHttpRequestException(
Should include a status code (413).

2020-07-22 20:48 UTC, Tratcher commented
Better. There should be existing tests for this scenario that you can update.

2020-07-23 01:59 UTC, Tratcher commented
Ah, like these:
https://dev.azure.com/dnceng/public/_build/results?buildId=741901&view=ms.vss-test-web.build-test-results-tab

2020-07-23 04:07 UTC, Tratcher commented
Nice. You're still missing test coverage for the new catch behavior. It's probably a combination of one of the tests you updated and something like this:
https://github.com/dotnet/aspnetcore/blob/8b7972064f068f76452eff7994263a5e4ee3ca46/src/Servers/HttpSys/test/FunctionalTests/ServerTests.cs#L197-L213

2020-07-30 23:29 UTC, Tratcher approved these changes

2020-07-30 23:29 UTC, merged

2020-07-30 23:29 UTC, Tratcher commented
Thanks