Remove Internal.AspNetCore.Analyzers
dotnet/aspnetcore pull request #24693
Opened 2020-08-07 22:07 UTC by pranavkm

This resolves build flakiness caused by referencing the analyzer:

```
2020-08-07T21:22:39.1149296Z ##[error].dotnet\sdk\5.0.100-rc.1.20379.10\Microsoft.Common.CurrentVersion.targets(4188,5): error MSB3026: (NETCORE_ENGINEERING_TELEMETRY=Build)
Could not copy "F:\workspace\_work\1\s\artifacts\obj\Internal.AspNetCore.Analyzers\Release\netstandard1.3\Internal.AspNetCore.Analyzers.dll"
to "F:\workspace\_work\1\s\artifacts\bin\Internal.AspNetCore.Analyzers\Release\netstandard1.3\Internal.AspNetCore.Analyzers.dll". Beginning retry 1 in 1000ms.
The process cannot access the file 'F:\workspace\_work\1\s\artifacts\bin\Internal.AspNetCore.Analyzers\Release\netstandard1.3\Internal.AspNetCore.Analyzers.dll' because it is being used by another process.
```

The analyzer checks if pubternal types are being exposed in public APIs. We no longer author pubternal types, so this is no longer a concern.

Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

Addresses #bugnumber (in this specific format)

2020-08-08 00:49 UTC, dougbu commented
Merging this addresses one bullet in #24608

2020-08-08 00:52 UTC, dougbu requested changes
Otherwise looks great❕

2020-08-08 00:52 UTC, dougbu commented on Directory.Build.props
> -    Condition="'$(DisablePubternalApiCheck)' != 'true'
Please remove `<DisablePubternalApiCheck>true</DisablePubternalApiCheck>` from the 5 places it appears.

2020-08-10 20:27 UTC, pranavkm commented
🆙 📅

2020-08-10 22:09 UTC, dougbu approved these changes

2020-08-10 22:12 UTC, dougbu commented
Weird. Something must have crept into 'master' which broke the `ThrowingSynchronousConnectionMiddlewareDoesNotCrashServer` tests. Can't see how that relates to changes in this PR.

2020-08-10 22:24 UTC, pranavkm commented
I pinged @halter73 on it. Quarantined it as part of https://github.com/dotnet/aspnetcore/pull/24757m tracked as part of https://github.com/dotnet/aspnetcore/issues/24758.

2020-08-11 03:08 UTC, merged