Backport fix on IAsyncEnumerable from 5.0 to 3.1 (PR 24926)
dotnet/aspnetcore pull request #25177
Opened 2020-08-24 00:38 UTC by tebeco

TL;DR
This might be rejected, but at least the PR is ready as the bug was discussed about on Gitter
This is also on `LTS` (since 5.0 will NOT be LTS)
eg: 
The team responsible for `AuthN / AuthZ Handler` usually refuse to work on non-LTS, so no `net5.0` for us :(

Addresses #25164

Summary of the changes:
> Found from a stackoverflow question.
> System.Linq.Async has a ToAsyncEnumerable method which returns a generic class that implements IAsyncEnumerable<T> which didn't work with our reflection logic.
> https://github.com/dotnet/reactive/blob/7ad606b3dcd4bb2c6ae9622f8a59db7f8f52aa85/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToAsyncEnumerable.cs#L34

Also:

> Before we were assuming if the type was generic then it must be an IAsyncEnumerable<> or some non-streaming type which is what that check was doing. But that was a wrong assumption since you can have a generic type that implements IAsyncEnumerable<> instead of being an IAsyncEnumerable directly. We then fallback to the logic below that statement that checks all interface types for IAsyncEnumerable<>. If you take a look at the added test case then you can see the structure of a type that failed the check before.

And finally I am aware of:
> I mean it's possible, it's just the servicing bar is unlikely to be met. https://github.com/dotnet/aspnetcore/blob/master/docs/Servicing.md#servicing-bar

2020-09-02 19:48 UTC, BrennanConroy commented
I'm not convinced we should bring this to shiproom for backporting. There is a single customer asking for it and there is a workaround provided.

2020-09-03 01:40 UTC, halter73 commented
I agree this is fairly low value. But on the other hand, it's very low risk. I wouldn't change when we patch next because of this issue, but if we're going to patch anyway, I'd want to take this.

2020-09-04 21:20 UTC, halter73 approved these changes

2020-09-04 21:21 UTC, BrennanConroy commented
@tebeco Can you change the base branch to release/3.0 please.

2020-09-04 21:23 UTC, halter73 requested changes
This looks good but it needs to target release/3.0.

2020-09-04 21:52 UTC, tebeco commented
on it

2020-09-04 22:24 UTC, tebeco commented
Currently rebasing,
For my curiosity may I ask why `3.0` it it's now "out of support" and LTS are 2.1 / 3.1 and current it 3.1 ?

2020-09-04 22:42 UTC, halter73 commented
Sorry, I should have said release/3.1.

2020-09-04 22:43 UTC, tebeco commented
sorry about that delay I did not check the base branch, In fact I'm surprised I managed to apply a diff on master while it was fixed in `5.0` :D 
i feel stupid

2020-09-04 22:45 UTC, tebeco commented
should be better like this
Sorry about that

2020-09-04 22:52 UTC, halter73 commented
> In fact I'm surprised I managed to apply a diff on master while it was fixed in 5.0

I'm surprised too. I wonder how that happened.

2020-09-04 22:58 UTC, tebeco commented
How bad can it go ....
![image](https://user-images.githubusercontent.com/2266487/92290006-e47bf480-ef12-11ea-9a3a-61717b6e725a.png)

2020-09-04 23:16 UTC, tebeco commented
> It's crazy that GitHub generated that "diff" when this was targeting master
oO right ... something else went wrong and it's a bit hard to find out what was it ...

cudo to @BrennanConroy

2020-09-04 23:31 UTC, tebeco commented
(restoring branch / running it to see if test fails locally too)
can't tell from build log if related or not

2020-09-04 23:38 UTC, BrennanConroy commented
The failures are due to some SameSite cookie issues due to Chrome updating. This PR wont pass until we merge some changes into 3.1 first. We'll re-run this when that happens.

2020-09-04 23:40 UTC, tebeco commented
do I need to change the format of the template and remove all the "MORE" from the PR description for the "servicing model" ?

2020-09-06 22:32 UTC, tebeco commented
unrelated
@halter73 you can check  gitextensions PR 8435 (avoiding linking unrelated PR)

2020-09-08 17:49 UTC, wtgodbe commented
/azp run

2020-09-08 20:21 UTC, wtgodbe commented
The 3 red jobs are from friday - weird that github is still showing them here. CI is actually green

2020-09-11 16:21 UTC, BrennanConroy approved these changes

2020-09-11 16:22 UTC, merged