TypeReference usage clarification
dotnet/aspnetcore pull request #25719
Opened 2020-09-09 05:47 UTC by kenegozi

This change makes TypeReference usage a little bit easier

- Marking it abstract make it so that usages cannot "forget" subclassing (or omitting the { } part). Previously the error message would be confusing as the supertype would be Object.
- Removing the instanceof check and relying on exception since instantiating TypeReference without a type parameter (new TypeReference() ) *is* exceptional as it goes against the intention of this class altogether.
- Added some clarification to the javadoc regarding intended usage, and a link to prior art for further reading.

Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

Addresses #bugnumber (in this specific format)

2020-09-09 05:47 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=25719) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=25719) before we can accept your contribution.<br/><br/>:x: kenegozi [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=25719)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=25719) it.</sub>

2020-09-09 16:57 UTC, wtgodbe commented on src/SignalR/clients/java/signalr/core/src/main/java/com/microsoft/signalr/TypeReference.java
> +     * To get the Type of Class Foo<Bar>, use the following syntax:
Looks like this javadoc syntax is off:

>   F:\workspace\_work\1\s\src\SignalR\clients\java\signalr\core\src\main\java\com\microsoft\signalr\TypeReference.java:24: error: unknown tag: Bar

2020-09-09 16:58 UTC, wtgodbe requested changes
This looks good, thanks! Once the javadoc issue is resolved I'll approve

2020-09-09 16:58 UTC, BrennanConroy commented
Do we want to move this to RC2?

2020-09-09 17:00 UTC, wtgodbe commented
> Do we want to move this to RC2?

Good point - I think that'd be good so that the YourPhone team can get this along with the rest of the rc2 changes.

@kenegozi can you retarget this to the `release/5.0-rc2` branch?

2020-09-09 23:58 UTC, kenegozi commented
no problem. I'll fix the thing and rebase onto rc2

2020-09-10 04:13 UTC, kenegozi commented
@wtgodbe thanks for pointing out the error message. I could not find the actual error message on github's UI nor at the azure pipelines page. Then when running `gradlew javadoc` locally it ran without the doclint option and passed as well. I had to run `javadoc TypeReference.java  -Xdoclint:all` to repro the error message locally.

2020-09-10 04:15 UTC, kenegozi commented
I see some failures in the CI report but they are at far-away parts of the codebase. Is HEAD on 5.0-rc2 consistently green?

2020-09-10 04:20 UTC, BrennanConroy commented
No worries, some machines weren't allocated in time and the build timed out. I've respun the timed out builds.

2020-09-10 15:06 UTC, kenegozi commented
Looks like another run is stuck at 11h of runtime :(

2020-09-10 16:26 UTC, wtgodbe commented
I just hit retry again - we've unfortunately been hit by some flakiness in machine availability recently 😦

2020-09-10 16:27 UTC, wtgodbe approved these changes

2020-09-10 20:19 UTC, wtgodbe commented
@Pilchie can we take this for RC2? It improves the docs, usability & correctness of the newly introduced `TypeReference`, which messagePack users can use to convert a Java Class to a Type.

2020-09-10 22:00 UTC, Pilchie commented
Approved for RC2.

2020-09-10 22:02 UTC, merged

2020-09-10 22:02 UTC, wtgodbe commented
Thanks @kenegozi!

2020-09-11 04:02 UTC, kenegozi commented
Do you need me to front-port it to the main development branch?

2020-09-11 04:06 UTC, Pilchie commented
Nope, we've got a bot that will handle that.  Thanks for the offer though!