Update ControllerActionInvoker
dotnet/aspnetcore pull request #27639
Opened 2020-11-09 09:42 UTC by ilonze

After the next filter is executed and the result is changed, the _actionExecutingContext.Result is still null. 

Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

Addresses #bugnumber (in this specific format)

2020-11-09 10:28 UTC, enisn approved these changes

2020-11-09 10:29 UTC, enisn commented
It looks right in theory

2020-11-09 11:12 UTC, ilonze commented
Hi!
It looks like merging is still blocked... need a review and someone with write access to merge this!
Thanks!

2020-11-09 13:31 UTC, davidfowl commented
Where's the test?

2020-11-09 17:13 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=27639) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=27639) before we can accept your contribution.<br/><br/>:x: ilonze [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=27639)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=27639) it.</sub>

2020-11-09 17:19 UTC, davidfowl commented
@ilonze Thanks! Can you fix up the PR comment? Is there a bug number for this?

2020-11-09 17:26 UTC, ilonze commented
@davidfowl Sorry! I haven't bug number.

2020-11-09 18:01 UTC, davidfowl commented
@ilonze Can you fix up the pull request comment as well?

2020-11-09 18:05 UTC, ilonze commented
@davidfowl Sorry! I'm edited.

2020-11-09 23:41 UTC, JamesNK commented on src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs
> +							else if (_actionExecutedContext != null && _actionExecutedContext.Result != null)
Replace tabs with spaces

2020-11-09 23:41 UTC, JamesNK commented on src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs
> +							else if (_actionExecutedContext != null && _actionExecutedContext.Result != null)
Replace tabs with spaces

2020-11-10 10:40 UTC, enisn approved these changes

2020-11-11 18:21 UTC, pranavkm requested changes
Hi, I asked some clarifying questions about this PR in the issue: https://github.com/dotnet/aspnetcore/issues/27647#issuecomment-725583408. Could you respond to it?

2020-11-12 02:23 UTC, ilonze commented
> Hi, I asked some clarifying questions about this PR in the issue: [#27647 (comment)](https://github.com/dotnet/aspnetcore/issues/27647#issuecomment-725583408). Could you respond to it?

Hi, My demo added to the issue: [#27647 (comment)](https://github.com/dotnet/aspnetcore/issues/27647#issuecomment-725784804)

2021-01-22 20:31 UTC, pranavkm approved these changes

2021-01-25 12:58 UTC, javiercn approved these changes

2021-01-25 14:42 UTC, davidfowl commented on src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs
> +                            else if (_actionExecutedContext != null && _actionExecutedContext.Result != null)
nit: could be simplified to:

```C#
if (_actionExecutedContext?.Result != null)
```

2021-01-25 14:43 UTC, javiercn commented on src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs
> +                            else if (_actionExecutedContext != null && _actionExecutedContext.Result != null)
💯 Pranav points :)

2021-01-26 18:28 UTC, pranavkm commented
@ilonze sorry for taking this long to get back to your PR. It looks like some of the tests in MVC are failing as a result of this change. Could you look?

2021-02-11 18:55 UTC, pranavkm commented
@ilonze feel free to reopen this PR once you've had a chance to look at the test failures.

2021-02-11 18:55 UTC, closed without merging