Get M.A.Mvc.Testing assembly from correct location
dotnet/aspnetcore pull request #30270
Opened 2021-02-18 17:39 UTC by captainsafia

2021-02-18 19:20 UTC, javiercn approved these changes
Great!

2021-02-18 19:21 UTC, javiercn requested changes
I take it back, we need to put the tasks assembly in the tasks folder. Otherwise it will be added as a reference

2021-02-18 20:47 UTC, javiercn approved these changes
I think it looks good!

Get @pranavkm to also take a quick look!

2021-02-19 21:54 UTC, pranavkm approved these changes

2021-02-19 21:54 UTC, merged