[2.1] Update baseline and SDK
dotnet/aspnetcore pull request #30779
Opened 2021-03-09 18:23 UTC by JunTaoLuo

https://github.com/dotnet/aspnetcore-internal/issues/3781

2021-03-09 18:41 UTC, dougbu requested changes

2021-03-09 18:54 UTC, JunTaoLuo commented on build/dependencies.props
> +    <SystemTextEncodingsWebPackageVersion>4.5.0</SystemTextEncodingsWebPackageVersion>
You mean repin?

2021-03-09 18:55 UTC, wtgodbe commented on build/dependencies.props
> +    <SystemTextEncodingsWebPackageVersion>4.5.0</SystemTextEncodingsWebPackageVersion>
And update it to 4.5.1

2021-03-09 18:58 UTC, dougbu commented on build/dependencies.props
> +    <SystemTextEncodingsWebPackageVersion>4.5.0</SystemTextEncodingsWebPackageVersion>
Yup and yup

2021-03-09 20:39 UTC, JunTaoLuo commented
@dougbu did we ever figure out how to fix the timeouts? If not I'm probably going to merge this as is.

2021-03-09 21:06 UTC, wtgodbe approved these changes

2021-03-09 23:33 UTC, BrennanConroy commented
https://github.com/dotnet/aspnetcore/pull/30164#issuecomment-791019893

2021-03-09 23:47 UTC, dougbu commented
@BrennanConroy's right. I recommend cherry-picking https://github.com/dotnet/aspnetcore/pull/30164/commits/5bafa2d364e6fd3e1bddfca0034b9a81b4e14db7 into this PR. Makes more sense here than in #30164 anyhow.

2021-03-10 03:07 UTC, dougbu approved these changes

2021-03-10 03:09 UTC, merged