[release/5.0] Merge, update baselines, SDK and runtimes
dotnet/aspnetcore pull request #30781
Opened 2021-03-09 19:21 UTC by dougbu

- aspnetcore-internal#3783
- Merge commit 'e882394a7bb38930da748291fe2c2ceaa6a80588' into 'release/5.0'
- Update `$(MicrosoftAspNetCoreAzureAppServicesSiteExtension31PackageVersion)`
- Update package baselines
- Update SDK and runtime versions

2021-03-09 19:49 UTC, dougbu commented on eng/Baseline.Designer.props
>    <ItemGroup Condition=" '$(PackageId)' == 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer' AND '$(TargetFramework)' == 'netcoreapp5.0' ">
These conditions are still wrong. Looks like the baseline generator in 5.0 is not up-to-date with the one in 3.1. I'll fix this as part of this PR.

2021-03-09 21:04 UTC, wtgodbe requested changes
Please change `ValidateBasline` to `true`

2021-03-09 21:45 UTC, wtgodbe commented
/azp run

2021-03-09 21:50 UTC, wtgodbe commented
> ##[error]src/Components/WebAssembly/Server/src/Microsoft.AspNetCore.Components.WebAssembly.Server.csproj(0,0): error NU1603: (NETCORE_ENGINEERING_TELEMETRY=Restore) Microsoft.AspNetCore.Components.WebAssembly.Server depends on Microsoft.NETCore.BrowserDebugHost.Transport (>= 5.0.4-servicing.21116.14) but Microsoft.NETCore.BrowserDebugHost.Transport 5.0.4-servicing.21116.14 was not found. An approximate best match of Microsoft.NETCore.BrowserDebugHost.Transport 5.0.5-servicing.21126.7 was resolved.

Thought I had already pushed everything. Looking

2021-03-09 22:12 UTC, wtgodbe commented
/azp run

2021-03-10 17:08 UTC, wtgodbe approved these changes

2021-03-10 17:38 UTC, merged