Bring back working DevServer packaging setup
dotnet/aspnetcore pull request #31043
Opened 2021-03-18 22:24 UTC by captainsafia

Bring back the changes introduced in https://github.com/dotnet/aspnetcore/pull/24816 to fix https://github.com/dotnet/aspnetcore/issues/30917.

2021-03-18 22:29 UTC, HaoK commented on src/Components/WebAssembly/DevServer/src/Microsoft.AspNetCore.Components.WebAssembly.DevServer.csproj
> +    <DoNotApplyWorkaroundsToMicrosoftAspNetCoreApp>true</DoNotApplyWorkaroundsToMicrosoftAspNetCoreApp>
nice property name haha

2021-03-18 22:29 UTC, HaoK approved these changes

2021-03-18 22:56 UTC, TanayParikh reviewed
LGTM

2021-03-18 23:12 UTC, dougbu requested changes
We need to talk about this more. Will break things pretty thoroughly at the next big version change and then again when we start targeting a new TFM.

2021-03-19 00:04 UTC, captainsafia commented
> We need to talk about this more. Will break things pretty thoroughly at the next big version change and then again when we start targeting a new TFM.

Yeah, for context, the plan was to do something tactical for preview3 since Blazor WASM apps are totally borked on IIS Express at the moment.

Do you have an idea for an alternate approach that we can include in preview3 to resolve this?

2021-03-19 00:21 UTC, dougbu commented
> Do you have an idea for an alternate approach that we can include in preview3 to resolve this?

I'm not sure how much from runtimeconfig.template.json makes it into the generated file. Might be possible to have the build auto-magically add the Microsoft.AspNetCore.App framework. Ideal would be to inject the latest version but could just use what we released in preview 2 along with the `rollForwardOnNoCandidateFx` setting.

Put another way, try checking the following into src/Components/WebAssembly/DevServer/src/runtimeconfig.template.json

``` json
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "6.0.0-preview.2.21154.6"
    },
    "rollForwardOnNoCandidateFx": 2
  }
```

2021-03-19 00:21 UTC, captainsafia commented
> We need to talk about this more. Will break things pretty thoroughly at the next big version change and then again when we start targeting a new TFM.

@pranavkm proposed modifying the runtime.config.json before packing the project to include the correct framework reference. Thoughts on this approach?

2021-03-19 00:22 UTC, dougbu commented
> > We need to talk about this more. Will break things pretty thoroughly at the next big version change and then again when we start targeting a new TFM.

> @pranavkm proposed modifying the runtime.config.json before packing the project to include the correct framework reference. Thoughts on this approach?

That would work too. I slightly prefer the static setup because it's less complicated.

2021-03-19 04:45 UTC, dougbu approved these changes
If it works i.e. the test failure in CI build is just flakiness, wonderful

2021-03-19 16:04 UTC, merged