Don't separately build arm64 installers
dotnet/aspnetcore pull request #31158
Opened 2021-03-23 19:07 UTC by JunTaoLuo

This should fix BAR push.

I think we should backport this to 3.1 as well. Although the error will only surface when we need to rebuild targeting pack in servicing which is very rare.

2021-03-23 19:12 UTC, wtgodbe approved these changes
Do the arm64 installers get built somewhere else?

2021-03-23 19:16 UTC, BrennanConroy commented
This will need to go into the 6.0-preview3 branch

2021-03-23 20:34 UTC, JunTaoLuo commented
Yes all msi installers are built in the x64/x86 step. In 3.1 we needed to build it as part of arm64 build since no other installers wouldbe building. I forgot to remove that as it merged cleanly 3.1->main.

2021-03-23 20:34 UTC, dougbu requested changes
This won't fix the actual problem because we're currently building the targeting packs in _every_ build job. It also sets us up for major problems in preview 3 and later because the ARM64 installers won't be included. Core issue is at https://github.com/dotnet/aspnetcore/blob/main/Directory.Build.targets#L82-L83 General problem after reverting recent problems there will be building the ARM64 installer inputs without shipping them i.e. excluding them from the asset manifest.

2021-03-23 20:42 UTC, JunTaoLuo commented
Ah I see, the change removed the duplications of `aspnetcore-targeting-pack-6.0.0-preview.3.21172.9.tar.gz` but the nupkgs are still being built as part of building on each individual platform.

2021-03-23 22:40 UTC, dougbu approved these changes
Looks better😃

You had a reason to mark Microsoft.AspNetCore.App.Ref and &hellip;Internal projects as packable in release/3.1, likely something about providing all inputs the installers needed. Was that reason invalid❔

2021-03-23 22:56 UTC, JunTaoLuo commented
I had to specifically mark Ref and Ref.Internal as packable in release/3.1 since we needed those zips built for arm64 but not any other platform. Usually all targeting pack is built together (zips and installers) in the x86/x64 leg. Hence the oddity in 3.1. However, in the 6.0 releases, there's no need for this special case.

2021-03-24 00:24 UTC, JunTaoLuo commented
The internal build artifacts look correct and the duplication has been resolved.

2021-03-24 00:24 UTC, merged

2021-03-24 16:15 UTC, BrennanConroy commented
@JunTaoLuo  I believe you need to manually forward port this to main