Update the Blazor WebAssembly app name to match the server
dotnet/aspnetcore pull request #33127
Opened 2021-05-28 22:30 UTC by mkArtakMSFT

We've had resolved this issue as part of https://github.com/dotnet/aspnetcore/pull/29764/files but the client project needs to be updated too.

2021-05-28 22:47 UTC, pranavkm approved these changes
Do you know where that name gets appears?

2021-05-28 23:00 UTC, TanayParikh approved these changes

2021-06-01 23:08 UTC, mkArtakMSFT commented
> Do you know where that name gets appears?

In VS New Project Dialog

2021-06-01 23:13 UTC, danroth27 requested changes

2021-06-01 23:13 UTC, danroth27 commented on src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/.template.config/template.json
> +  "defaultName": "BlazorApplication",
```suggestion
  "defaultName": "BlazorApp",
```

For consistency with https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/.template.config/template.json#L448

2021-06-02 19:29 UTC, mkArtakMSFT commented
Thanks @danroth27.
Can you sign-off now so that I can merge this?

2021-06-02 19:42 UTC, danroth27 approved these changes

2021-06-02 21:52 UTC, merged