Added copy parameters to enable parallel build
dotnet/aspnetcore pull request #33758
Opened 2021-06-22 16:11 UTC by dashkodo

- [ ] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**PR Title**
Added parameters to Copy task that is executed for setting up correct dependency environment in the tests.

**PR Description**
When enabling multiple msbuild nodes it could fail due to locking "xxx.deps.json" files
We have faced with this issue using latest version of microsoft.aspnetcore.mvc.testing nuget package
C:\ZZZZ\nuget\microsoft.aspnetcore.mvc.testing\5.0.7\build\net5.0\Microsoft.AspNetCore.Mvc.Testing.targets(56, 5): error MSB3027: Unable to copy file "D:\XXXX\bin\Release\YYYY.deps.json" to "bin\Release\YYYY.deps.json". The process cannot access the file 'bin\Release\YYYY.deps.json' because it is being used by another process.

Addresses #33757

2021-06-24 08:20 UTC, javiercn requested changes
Thanks for the contribution.

I've made a suggestion since we normally use `_` for things we don't want people to depend on or configure individually (like this).

The default value should also come from the standard `CreateHardLinksIfPossible` (or however is named in copy files) since that's the single switch users turn on or off

2021-06-24 08:20 UTC, javiercn commented on src/Mvc/Mvc.Testing/src/Microsoft.AspNetCore.Mvc.Testing.targets
> +    </PropertyGroup>
```suggestion
    <PropertyGroup>
        <_CreateHardLinksForMvcCopyDependencyFilesIfPossible Condition="'$(CreateHardLinksForMvcCopyDependencyFilesIfPossible)' == ''">false</_CreateHardLinksForMvcCopyDependencyFilesIfPossible>
        <_CreateSymbolicLinksForMvcCopyDependencyFilesIfPossible Condition="'$(CreateSymbolicLinksMvcCopyDependencyFilesIfPossible)' == ''">false</_CreateSymbolicLinksForMvcCopyDependencyFilesIfPossible>
    </PropertyGroup>
```

2021-06-24 08:20 UTC, javiercn commented on src/Mvc/Mvc.Testing/src/Microsoft.AspNetCore.Mvc.Testing.targets
> +       Condition="Exists('%(DepsFilePaths.FullPath)')" />
```suggestion
    <Copy SourceFiles="%(DepsFilePaths.FullPath)"
       DestinationFolder="$(OutDir)"
       UseHardlinksIfPossible="$(_CreateHardLinksForMvcCopyDependencyFilesIfPossible)"
       UseSymboliclinksIfPossible="$(_CreateSymbolicLinksForMvcCopyDependencyFilesIfPossible)"
       Condition="Exists('%(DepsFilePaths.FullPath)')" />
```

2021-07-01 16:02 UTC, dashkodo commented
I could not find any generict `CreateHardLinksIfPossible`
only specialized `CreateHardLinksFor_Something_IfPossible` are located in targets.

2022-01-21 15:05 UTC, pranavkm commented
@dashkodo feel free to reopen this PR once you've had a chance to address this feedback:

> The default value should also come from the standard CreateHardLinksIfPossible (or however is named in copy files) since that's the single switch users turn on or off

2022-01-21 15:05 UTC, closed without merging

2022-12-27 18:15 UTC, dashkodo commented
Hi @pranavkm  I've added defaults. Hope it's matching your expectation

2022-12-27 18:21 UTC, dashkodo commented
@javiercn Hi, Let me know if any further changes required.
BTW I have no permission to reopen pull request. Could you suggest what is the better here - create new one or open this?