Moved /src/Http/Features/ to /src/Extensions/Features/
dotnet/aspnetcore pull request #34444
Opened 2021-07-16 23:33 UTC by vstr

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**PR Title**
Moved /src/Http/Features/ to /src/Extensions/Features/

**PR Description**
Moved Microsoft.Extensions.Features projects to new location, updated references for sln, slnf and props.

Addresses #34423

2021-07-17 02:26 UTC, Tratcher approved these changes
Very thorough, thanks!

2021-07-18 23:08 UTC, Tratcher commented
Looks like this needs one more step to fix the Code Check failures.

https://github.com/dotnet/aspnetcore/blob/main/docs/ReferenceResolution.md
> Run eng/scripts/GenerateProjectList.ps1 (or build.cmd /t:GenerateProjectList) when adding new projects

Can you give that a try?

2021-07-19 06:54 UTC, vstr commented
Yes, trying to fix the build for few days, `GenerateProjectList.ps1` removes `Microsoft.Extensions.Features` from `eng\ProjectReferences.props` and `eng\SharedFramework.Local.props` for some reason. After that the build obviously fails locally.

The log message from 'azure-pipelines / aspnetcore-ci' says 
_"eng\ProjectReferences.props(,): error : Generated code is not up to date in eng/ProjectReferences.props. You might need to regenerate the reference assemblies or project list (see docs/ReferenceAssemblies.md and docs/ReferenceResolution.md)"_

From `docs/ReferenceResolution.md`:
- GenerateProjectList.ps1 removes `Microsoft.Extensions.Features`
- BaseLineGenerator - we don't have 'Microsoft.Extensions.Features' in `Baseline.xml` so there seems no need to run it.

There is no such doc as `docs/ReferenceAssemblies.md` (looks like the log message needs to be updated)

Any ideas on what may be missing here?

2021-07-19 17:16 UTC, dougbu commented
> Any ideas on what may be missing here?

You need to update the two `Include` lists in https://github.com/dotnet/aspnetcore/blob/6bf34a09951ef0752c856b34a2cef85de164cd48/eng/Build.props#L155-L240 to include `$(RepoRoot)src\Extensions\**\*.csproj;` and `$(RepoRoot)src\WebEncoders\**\src\*.csproj;`, respectively.

2021-07-19 17:59 UTC, vstr commented
Thank you @dougbu! it now builds without issues locally.

2021-07-19 19:25 UTC, dougbu requested changes

2021-07-19 19:25 UTC, dougbu commented on eng/Build.props
> +                          $(RepoRoot)src\WebEncoders\**\src\*.csproj;
```suggestion
                          $(RepoRoot)src\Extensions\**\*.csproj;
```

2021-07-19 19:25 UTC, dougbu commented on eng/Build.props
> +                          $(RepoRoot)src\WebEncoders\**\src\*.csproj;
```suggestion
                          $(RepoRoot)src\Extensions\**\src\*.csproj;
```

2021-07-19 19:27 UTC, dougbu commented on eng/Build.props
> +                          $(RepoRoot)src\Extensions\**\*.csproj
```suggestion
                          $(RepoRoot)src\Extensions\**\*.csproj;
```

2021-07-19 19:28 UTC, dougbu approved these changes
Sorry for the extra commits, something went wrong in GitHub UI and it didn't let me just delete the extra lines.

2021-07-19 19:33 UTC, vstr commented
Thank you for your input anyway!

2021-07-19 20:28 UTC, dougbu commented
Still need to run the update script @vstr

2021-07-19 22:13 UTC, vstr commented
Finally all checks passed, thank you @dougbu , @Tratcher !

2021-07-19 22:15 UTC, merged