HTTP/3: Http3Stream pooling
dotnet/aspnetcore pull request #34576
Opened 2021-07-21 02:45 UTC by JamesNK

This builds on top of the new `IPersistentStateFeature`.

Http3Stream and many of its associated types (pipes, output producer, decoder) are now reused between requests.

I will get benchmarks comparing allocations before and after.

2021-07-21 17:44 UTC, Tratcher approved these changes
Seems OK in general once the build is fixed. I'm curious to see the benchmarks.

2021-07-22 18:17 UTC, halter73 commented on src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs
> +                            Debug.Assert(persistentStateFeature != null, $"Required {nameof(IPersistentStateFeature)} not on stream context.");
This seems too possible to just assert given the transport is pluggable. Let's null-check and throw.

2021-07-22 18:17 UTC, halter73 approved these changes
I also look forward to the benchmarks.

2021-07-23 18:00 UTC, dougbu requested changes
New and renamed files need MIT license headers

2021-07-23 20:43 UTC, JamesNK commented
I thought I had already updated old files. Which ones still need to be updated?

2021-07-23 20:54 UTC, dougbu approved these changes
> I thought I had already updated old files. Which ones still need to be updated?

I must have looked at this and still had an older copy of the changes cached. Sorry.

I don't see another way to remove my changes request and am signing off only on the headings.

2021-07-23 23:16 UTC, JamesNK commented
Before - 300mb allocated for 10,000 requests
![image](https://user-images.githubusercontent.com/303201/126849550-90e72e93-bed6-4d6e-8d7d-4f1a561e35cc.png)

After - 50mb allocated for 10,000 requests
![image](https://user-images.githubusercontent.com/303201/126849539-06550b85-cf56-4e3d-af9a-f74a06cd83f4.png)

2021-07-24 02:53 UTC, merged