[release/6.0-rc1] Binding support for 'bool' values with InputRadioGroup and InputSelect
dotnet/aspnetcore pull request #35523
Opened 2021-08-19 18:55 UTC by MackinnonBuck

## Description

Added support for `bool` value bindings with the Blazor `InputRadioGroup` and `InputSelect` components.

## Customer Impact

Having radio/select inputs with only two choices is a fairly common scenario (true/false, yes/no prompts). In these cases, `bool` is an appropriate type for the value bound to the selected choice.

## Regression?
- [ ] Yes
- [X] No

## Risk
- [ ] High
- [ ] Medium
- [X] Low

This change is almost purely additive, so it's unlikely that it will break other functionality.

## Verification
- [X] Manual (required)
- [X] Automated

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [X] N/A

Addresses #34816

2021-08-19 19:51 UTC, pranavkm commented
FYI @davidfowl for approval.

2021-08-19 20:02 UTC, pranavkm approved these changes

2021-08-19 20:07 UTC, davidfowl commented
Approved. I dunno if I should be using servicing approved 😄

2021-08-19 20:07 UTC, davidfowl approved these changes

2021-08-19 20:26 UTC, BrennanConroy commented
Looks like you didn't add a new API, but added an override which modified the unshipped file. Unfortunately this triggered the "don't modify APIs" check that we do for servicing branches.

We can probably modify https://github.com/dotnet/aspnetcore/blob/721c539f0f0aff1fbec77b7f4f6263ec5abec08d/eng/scripts/CodeCheck.ps1#L216 to allow `rc*` branches

2021-08-19 21:56 UTC, BrennanConroy commented on eng/scripts/CodeCheck.ps1
> +                if ($targetBranch -like 'release*' -and $targetBranch -notlike '*preview*' -and $targetBranch -notlike '*rc*' -and $file -like '*PublicAPI.Unshipped.txt') {
cc @wtgodbe

2021-08-19 22:20 UTC, wtgodbe commented on eng/scripts/CodeCheck.ps1
> +                if ($targetBranch -like 'release*' -and $targetBranch -notlike '*preview*' -and $targetBranch -notlike '*rc*' -and $file -like '*PublicAPI.Unshipped.txt') {
CC @dougbu as well

2021-08-19 23:52 UTC, BrennanConroy requested changes, later dismissed
I'm suspicious of this change, there are over 300 test failures in Components that look to have started around when this PR was being worked on.

You can see here on a Monday build of the PR https://dev.azure.com/dnceng/public/_build/results?buildId=1296055&view=results the tests were failing, and looking at any other test run of Components that don't have these changes there are nowhere near 300 test failures.

2021-08-20 00:15 UTC, MackinnonBuck commented
Hm, this is strange. Even if the tests surrounding this change broke, I'm not sure why it would cause 300 seemingly unrelated tests to fail.

I'll investigate this as soon as I can to find out if there's something here causing the issues.

2021-08-20 00:27 UTC, MackinnonBuck commented
Running on my machine locally, all tests except 1 pass.

2021-08-20 00:59 UTC, BrennanConroy commented
Ok, after looking at more builds I think it's https://github.com/dotnet/aspnetcore/pull/35414 that caused the issues.

2021-08-20 21:19 UTC, merged