Fix templates with Windows auth option
dotnet/aspnetcore pull request #37607
Opened 2021-10-16 00:33 UTC by sebastienros

Fixes #37556

2021-10-16 01:07 UTC, HaoK approved these changes

2021-10-16 01:08 UTC, HaoK commented
@sebastienros I got that error in the past, I think you just need to uninstall all older 6.0 sdks, as I think that was how I got rid of that error

2021-10-16 04:58 UTC, timheuer submitted a review, later dismissed

2021-10-16 05:25 UTC, Tratcher commented
Other templates with windows auth:
https://github.com/dotnet/aspnetcore/blob/f306bfff08514a8edcb58c716decdb1a712e076f/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/Properties/launchSettings.json#L4
https://github.com/dotnet/aspnetcore/blob/f306bfff08514a8edcb58c716decdb1a712e076f/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-FSharp/Properties/launchSettings.json#L4
https://github.com/dotnet/aspnetcore/blob/f306bfff08514a8edcb58c716decdb1a712e076f/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Properties/launchSettings.json#L5
https://github.com/dotnet/aspnetcore/blob/f306bfff08514a8edcb58c716decdb1a712e076f/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-FSharp/Properties/launchSettings.json#L5

2021-10-18 15:55 UTC, pranavkm requested changes
The package version looks suspect

2021-10-18 17:23 UTC, pranavkm approved these changes

2021-10-18 21:59 UTC, Tratcher approved these changes

2021-10-19 00:08 UTC, merged