Fix AppHost pack prebuilt usage in source-build
dotnet/aspnetcore pull request #37672
Opened 2021-10-19 03:30 UTC by dagood

# Fix AppHost pack prebuilt usage in source-build

This change removes the `NetCoreTargetingPackRoot` override in some cases during source-build to avoid unnecessarily downloading the apphost pack as a prebuilt dependency. I also updated the comment on the override to be more descriptive (based on `git blame`) and added details on why/when it needs to be disabled for source-build.

* For https://github.com/dotnet/source-build/issues/2524
* PR to add this change to 6.0.1xx SDK: https://github.com/dotnet/installer/pull/12441

/cc @dougbu

2021-10-19 15:42 UTC, Pilchie commented
Looks fine to me, but would like @wtgodbe or @dougbu to sign off on it.

2021-10-19 21:26 UTC, wtgodbe approved these changes

2021-10-20 20:20 UTC, dougbu requested changes

2021-10-20 21:21 UTC, dagood commented
@dougbu @wtgodbe This is ready for another pass. I'm running it through a tarball build in https://github.com/dotnet/installer/pull/12469 and locally.

2021-10-20 21:26 UTC, wtgodbe approved these changes

2021-10-21 01:23 UTC, dougbu approved these changes

2021-10-21 20:35 UTC, merged