Un-quarantine `CanHandleErrorsInlineInErrorBoundaryContent`
dotnet/aspnetcore pull request #38137
Opened 2021-11-05 20:55 UTC by TanayParikh

Fixes https://github.com/dotnet/aspnetcore/issues/34870

2021-11-05 21:28 UTC, captainsafia approved these changes

2021-11-05 22:34 UTC, pranavkm requested changes
Can we hold off on merging this for a little bit?

2021-11-05 23:10 UTC, TanayParikh commented
> Can we hold off on merging this for a little bit?

Sure. What's wrong?

2021-11-05 23:11 UTC, TanayParikh commented
Oh is it to avoid merge conflicts in https://github.com/dotnet/aspnetcore/pull/38076?

2021-11-06 00:53 UTC, pranavkm approved these changes

2021-11-06 13:40 UTC, merged