ContentResult doc: see cref="Microsoft.AspNetCore.Http.StatusCodes"
dotnet/aspnetcore pull request #38828
Opened 2021-12-05 09:51 UTC by yecril71pl

# ContentResult doc: see cref="Microsoft.AspNetCore.Http.StatusCodes"

- [X] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Add a link to [StatusCodes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.statuscodes) to the description of [ContentResult.StatusCode](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.contentresult.statuscode#definition),

## Description

It is better to use constants provided by the library than raw numbers, let the reader know where they are defined!

Not worth a bug.

2021-12-06 22:39 UTC, mkArtakMSFT approved these changes
Thanks for your PR, @yecril71pl.

2021-12-06 22:40 UTC, mkArtakMSFT commented on src/Mvc/Mvc.Core/src/ContentResult.cs
> +    /// Gets or sets the <see cref="Microsoft.AspNetCore.Http.StatusCodes" >HTTP status code</see >.
```suggestion
    /// Gets or sets the <see cref="Microsoft.AspNetCore.Http.StatusCodes">HTTP status code</see >.
```

2021-12-06 22:42 UTC, mkArtakMSFT requested changes
Actually, it looks like your comment tags are inconsistent. Please make sure they all follow consistent styling, matching the existing style used in the document.

2021-12-06 22:46 UTC, yecril71pl commented
> Actually, it looks like your comment tags are inconsistent. Please make sure they all follow consistent styling, matching the existing style used in the document.

I am not sure what you mean.  The document is fairly short.

2021-12-06 23:49 UTC, mkArtakMSFT commented on src/Mvc/Mvc.Core/src/ContentResult.cs
> +    /// Gets or sets the <see cref="Microsoft.AspNetCore.Http.StatusCodes" >HTTP status code</see >.
```suggestion
    /// Gets or sets the <see cref="Microsoft.AspNetCore.Http.StatusCodes">HTTP status code</see >.
```

2021-12-06 23:50 UTC, mkArtakMSFT commented
There are differences between the `see` tags on lines 12 and 28.

2021-12-08 18:09 UTC, mkArtakMSFT commented
Closing as this change is now included in https://github.com/dotnet/aspnetcore/pull/38852/files

2021-12-08 18:09 UTC, closed without merging