Update KnownRuntimePack as part of updating KnownFrameworkReference
dotnet/aspnetcore pull request #39965
Opened 2022-02-03 18:16 UTC by pranavkm

2022-02-03 18:53 UTC, wtgodbe commented
https://dev.azure.com/dnceng/public/_build/results?buildId=1590349&view=results tests this workaround against the commits from https://github.com/dotnet/aspnetcore/pull/39853 pre-SDK update

2022-02-03 19:15 UTC, dougbu requested changes
It's not clear what you intend @pranavkm. As-is, the change does nothing because the `%(LatestRuntimeFrameworkVersion)` metadata is updated earlier in exactly the same way.

https://github.com/dotnet/aspnetcore/pull/39965/files#diff-9fb67cbc0a7ba3b793455ec41e7f36e1d019d5152674d669551810b308510d37R44-R45

2022-02-03 20:24 UTC, pranavkm commented
@dougbu the targets currently update `KnownFrameworkReference` but not `KnownRuntimePacks`. In a Blazor WASM app, the latter is used to resolve the rid-specific runtime pack (Microsoft.NETCore.App.Mono.browser-wasm). Screenshot of the build logs before this change:

![image](https://user-images.githubusercontent.com/174281/152422928-8a15fcbd-2cd7-4227-9007-2a99847ca2d0.png)

2022-02-03 20:33 UTC, dougbu approved these changes
Ah, I understand now. Do we need to do this w/ the `@(KnownAppHostPack)` item for the default Core TFM too❔

2022-02-03 20:35 UTC, pranavkm commented
Further details - the version for `KnownRuntimePacks` currently from the value the SDK bakes in. With a blazor app, it currently compiles using the version of the runtime specified by the targeting park that we override, but runs against the version from the SDK. This is problematic in that we're not testing blazor against new runtime ingestions. Additionally, it also prevents runtime insertions when the targeting pack and the runtime pack don't align. https://github.com/dotnet/aspnetcore/pull/39853 was a recent example of this.

2022-02-03 20:40 UTC, pranavkm commented
> Do we need to do this w/ the @(KnownAppHostPack)

I suppose we should - it's also got the SDK-specified version. That said, I don't know how that package gets used in the build.

2022-02-03 20:46 UTC, dougbu commented
> I don't know how that package gets used in the build.

I'm not positive either. I suspect your new commit will primarily affect tests that execute `dotnet {something}`.

@wtgodbe anything we should be concerned about❔ For example, are there cases where the versions won't align❔ Versions for the app host, runtime pack, and framework reference all match in the couple of SDKs I checked. Just wondering if I'm missing anything in how dotnet/runtime pushes new packages during servicing.

2022-02-03 20:48 UTC, dougbu commented on eng/tools/GenerateFiles/Directory.Build.targets.in
> +    </KnownRuntimePack>
```suggestion
        Condition=" '%(TargetFramework)' == '${DefaultNetCoreTargetFramework}' ">${MicrosoftNETCoreAppRuntimeVersion}</AppHostPackVersion>
    </KnownAppHostPack>
```

2022-02-03 21:25 UTC, wtgodbe commented
I'm not aware of any reason the runtime versions in an SDK would mismatch across ApphostPack/Runtime pack/Framework Reference - @dsplaisted any corner cases we should be aware of?

2022-02-03 21:29 UTC, wtgodbe commented
Didn't realize components-e2e was the failing job, here's the real test: https://dev.azure.com/dnceng/public/_build/results?buildId=1590790&view=results

2022-02-03 22:46 UTC, pranavkm commented
@dougbu / @wtgodbe good to merge?

2022-02-03 23:25 UTC, wtgodbe approved these changes

2022-02-03 23:25 UTC, wtgodbe commented
Test build worked, merge away

2022-02-03 23:25 UTC, merged

2022-02-04 13:30 UTC, dsplaisted commented
> I'm not aware of any reason the runtime versions in an SDK would mismatch across ApphostPack/Runtime pack/Framework Reference - @dsplaisted any corner cases we should be aware of?

I think those versions will always be the same.  This looks good to me.