Refactor : Enable CA2249
dotnet/aspnetcore pull request #40009
Opened 2022-02-05 06:43 UTC by ShreyasJejurkar

1. Enables CA2249
2. formatted `.editorconfig`

2022-02-05 07:14 UTC, ShreyasJejurkar commented
Maybe need to suppress the rule for this instance! Any thoughts!? @pranavkm 

https://github.com/dotnet/aspnetcore/blob/8e8a7c3bbee3ec17ea4593789929dc15284ef05a/src/Middleware/Rewrite/src/UrlActions/RedirectAction.cs#L55-L56

2022-02-05 14:34 UTC, pranavkm requested changes

2022-02-05 14:34 UTC, pranavkm commented on .editorconfig
> +
Could you undo this? The spaces were meant to make comments or description much clearer, but these are all suppressions for tests which don't need that.

2022-02-05 14:34 UTC, pranavkm commented on .editorconfig
> +dotnet_diagnostic.CA2249.severity = warning
Can you order it so it appears around line 215 in this file?

2022-02-05 14:34 UTC, pranavkm commented on src/Http/Http.Abstractions/src/HostString.cs
> +            else if (uriComponent.Contains("xn--"))
```suggestion
            else if (uriComponent.Contains("xn--", StringComparison.Ordinal))
```

2022-02-05 14:34 UTC, pranavkm commented on src/Middleware/Rewrite/src/RewriteRule.cs
> +            if (result.Contains(Uri.SchemeDelimiter))
```suggestion
            if (result.Contains(Uri.SchemeDelimiter, StringComparison.Ordinal))
```

2022-02-05 14:34 UTC, pranavkm commented on src/Middleware/Rewrite/src/UrlActions/RewriteAction.cs
> +        if (pattern.Contains(Uri.SchemeDelimiter))
```suggestion
        if (pattern.Contains(Uri.SchemeDelimiter, StringComparison.Ordinal))
```

2022-02-05 14:34 UTC, pranavkm commented on src/Mvc/Mvc.TagHelpers/src/TagHelperOutputExtensions.cs
> +        if (SpaceChars.Any(classValue.Contains) || encodedSpaceChars.Any(value => classValue.Contains(value)))
```suggestion
        if (SpaceChars.Any(classValue.Contains) || encodedSpaceChars.Any(value => classValue.Contains(value, StringComparison.Ordinal)))
```

2022-02-05 14:34 UTC, pranavkm commented on src/Mvc/Mvc.TagHelpers/src/TagHelperOutputExtensions.cs
> +        if (SpaceChars.Any(classValue.Contains) || encodedSpaceChars.Any(value => classValue.Contains(value)))
```suggestion
        if (SpaceChars.Any(classValue.Contains) || encodedSpaceChars.Any(value => classValue.Contains(value, StringComparison.Ordinal)))
```

2022-02-05 19:56 UTC, pranavkm approved these changes

2022-02-05 21:41 UTC, merged

2022-02-06 06:07 UTC, ShreyasJejurkar commented
Thanks, @pranavkm taking care of it. Sorry for the delay from my side. I guess we live in totally opposite timezone, I am in India! 

But anyway thanks for taking care and merging!