Check jdk is correctly installed
dotnet/aspnetcore pull request #40550
Opened 2022-03-04 23:41 UTC by sebastienros

Fixes #36331

2022-03-04 23:45 UTC, dougbu requested changes

2022-03-04 23:45 UTC, dougbu commented on eng/scripts/InstallJdk.ps1
>          Remove-Item -Force -Recurse $installDir
Don't remove `$installDir` variable

2022-03-04 23:49 UTC, sebastienros commented on eng/scripts/InstallJdk.ps1
>          Remove-Item -Force -Recurse $installDir
right ;)

2022-03-04 23:52 UTC, dougbu approved these changes

2022-03-04 23:52 UTC, dougbu commented on eng/scripts/InstallJdk.ps1
> +$javacExe = "$repoRoot\.tools\jdk\win-x64\bin\javac.exe"
nit: Use `$installDir` here

2022-03-08 18:01 UTC, wtgodbe approved these changes

2022-03-08 19:34 UTC, merged