Diff TestGroupName for project templates tests
dotnet/aspnetcore pull request #42214
Opened 2022-06-15 18:57 UTC by DamianEdwards

Attempt to fix project templates tests not showing up in CI build results.

2022-06-15 20:29 UTC, BrennanConroy requested changes
Likely need to update https://github.com/dotnet/aspnetcore/blob/main/eng/Build.props#L197

2022-06-15 20:33 UTC, dougbu commented
Correct @BrennanConroy. Sorry @DamianEdwards that this wasn't the right fix. This is helpful but changing that one line might be enough.

(<https://dev.azure.com/dnceng/public/_build/results?buildId=1827055&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=e4ee6667-9b0a-5a6e-4e24-bcba939f2af2> doesn't mention the word "templates" at all. Confirmed same checking a couple of the Helix work item lists.)

2022-06-15 22:00 UTC, BrennanConroy approved these changes

2022-06-16 03:09 UTC, TanayParikh approved these changes

2022-06-16 03:36 UTC, merged