Reuse failed auth results in AuthN
dotnet/aspnetcore pull request #43269
Opened 2022-08-13 20:16 UTC by Kahbazi

2022-08-13 20:22 UTC, davidfowl approved these changes
Keep these changes coming 👍🏾

2022-08-14 05:46 UTC, davidfowl requested changes
Turns out you can mutate these results 😢

2022-08-14 06:24 UTC, Kahbazi commented
> Turns out you can mutate these results 😢

I can't see how! Could you please elaborate? Is it because of the `Exception` object? I would argue that even in the clone method the Exception remains the same instance.

2022-08-14 14:15 UTC, davidfowl approved these changes

2022-08-15 23:11 UTC, Tratcher reviewed
Can you change AuthenticateResult.NoResult to cache?

There's a theoretical issue with caching AuthenticateResult, it can reference mutable structures like ClaimsPrincipal, AuthenticationProerties, Exception, etc.. NoResult, Skipped, and Handled might be the only cases truly safe to cache because they don't hold any mutable objects. That might be worth overlooking for extremely common scenarios. Are any of these failures especially common?

2022-08-15 23:11 UTC, Tratcher commented on src/Security/Authentication/Certificate/src/AuthenticateResults.cs
> +    internal static AuthenticateResult NoSelfSigned = AuthenticateResult.Fail("Options do not allow self signed certificates.");
Style: Why define these in separate classes if they're only used in one class?

2022-08-15 23:11 UTC, Tratcher commented on src/Security/Authentication/Core/src/HandleRequestResult.cs
> +    private static readonly HandleRequestResult _noResult = new() { None = true };
Style: I think we use "NoResult" for class statics, and "_noResult" for class fields.

2022-08-15 23:30 UTC, Tratcher approved these changes

2022-08-15 23:30 UTC, merged

2022-08-16 06:24 UTC, Kahbazi commented
> Can you change AuthenticateResult.NoResult to cache?

@Tratcher I've done that in this PR https://github.com/dotnet/aspnetcore/pull/43268