Wait to dispose RequestAborted CTS
dotnet/aspnetcore pull request #4447
Opened 2018-12-05 23:52 UTC by halter73

Partially Addresses #4422

2018-12-05 23:52 UTC, halter73 commented
@muratg I would like to get this into a 2.2 patch.

2018-12-05 23:56 UTC, natemcmaster requested changes
Can you make sure the affected assemblies are added to the list in https://github.com/aspnet/AspNetCore/blob/release/2.2/eng/PatchConfig.props?

2018-12-05 23:57 UTC, Tratcher approved these changes

2018-12-05 23:57 UTC, Tratcher commented on src/Servers/Kestrel/Core/test/Http1ConnectionTests.cs
> +#endif
#else TFMs need updating.

2018-12-06 00:03 UTC, halter73 commented
@natemcmaster It's nice not to have to switch repos anymore.

2018-12-06 00:09 UTC, natemcmaster approved these changes

2018-12-06 19:44 UTC, vivmishra commented
Approved for 2.2.2. 

We will take the CoreCLR fix still in 2.2.1. 
https://github.com/dotnet/coreclr/pull/21417

2019-01-15 00:01 UTC, dougbu commented on eng/PatchConfig.props
> +      Microsoft.AspNetCore.Server.Kestrel.Core;
No, your `release/2.2` branch is behind. Please rebase then add this to the new block that's for 2.2.2.

2019-01-15 22:54 UTC, merged