Remove old 1.x auth stack
dotnet/aspnetcore pull request #4485
Opened 2018-12-07 00:02 UTC by HaoK

Fixes https://github.com/aspnet/AspNetCore/issues/3999

@Tratcher

2018-12-07 00:15 UTC, Tratcher requested changes
All of the servers implemented IHttpAuthenticationFeature, you'll need to remove the property there as well.

2018-12-07 00:38 UTC, HaoK commented
Updated HttpSys and IIS to remove the Handler property

2018-12-07 01:42 UTC, Tratcher commented
And kestrel?

2018-12-07 18:51 UTC, HaoK commented
I couldn't see anything obvious that needed updating in kestrel and it didn't fail in building...  PR validation looks like it failed just due to breaking changes for the removal, fixing those now

2018-12-07 19:05 UTC, Tratcher commented
I guess in Kestrel it's only stored in the collection feature collection, it's not actually implemented. https://github.com/aspnet/KestrelHttpServer/search?q=IHttpAuthenticationFeature&unscoped_q=IHttpAuthenticationFeature

2018-12-07 22:15 UTC, Tratcher approved these changes

2018-12-08 18:44 UTC, PinpointTownes commented on src/Http/Http.Features/src/breakingchanges.netcore.json
> +      "Kind": "Removal"
Invalid JSON?

2018-12-08 18:45 UTC, PinpointTownes commented
![](https://media.giphy.com/media/10hO3rDNqqg2Xe/giphy.gif)

:+1: that was an incredible source of pain for users not familiar with the Auth 2.0 "grand refactoring".

2018-12-12 20:42 UTC, Tratcher commented
```
2018-12-12T00:52:00.4744658Z   D:\a\1\s\src\Security\src\Microsoft.AspNetCore.Authentication.JwtBearer\JwtBearerOptions.cs(103,24): error CS1574: XML comment has cref attribute 'AuthenticationProperties' that could not be resolved [D:\a\1\s\src\Security\src\Microsoft.AspNetCore.Authentication.JwtBearer\Microsoft.AspNetCore.Authentication.JwtBearer.csproj]
2018-12-12T00:52:00.4745720Z   D:\a\1\s\src\Security\src\Microsoft.AspNetCore.Authentication.Twitter\Messages\RequestToken.cs(4,33): error CS0234: The type or namespace name 'Authentication' does not exist in the namespace 'Microsoft.AspNetCore.Http' (are you missing an assembly reference?) [D:\a\1\s\src\Security\src\Microsoft.AspNetCore.Authentication.Twitter\Microsoft.AspNetCore.Authentication.Twitter.csproj]
2018-12-12T00:52:00.4905085Z   D:\a\1\s\src\Security\src\Microsoft.AspNetCore.Authentication.Twitter\Messages\RequestTokenSerializer.cs(6,33): error CS0234: The type or namespace name 'Authentication' does not exist in the namespace 'Microsoft.AspNetCore.Http' (are you missing an assembly reference?) [D:\a\1\s\src\Security\src\Microsoft.AspNetCore.Authentication.Twitter\Microsoft.AspNetCore.Authentication.Twitter.csproj]
2
```

2018-12-13 22:09 UTC, HaoK commented
@natemcmaster are the test failures expected at this point, pr-validation-temp passed, is this PR ok to merge?

2018-12-13 22:19 UTC, natemcmaster commented
Depends on which tests failed and why. I recommend comparing your PR with https://github.com/aspnet/AspNetCore-Internal/labels/test-failure to see if failures are known or not.

2018-12-13 23:04 UTC, HaoK commented
This PR is just removing obsolete apis so its either a compilation break or no change, the failures mostly appear to be in kestrel so should be fine

2018-12-13 23:23 UTC, Tratcher commented
The IIS failures look related.
https://dnceng.visualstudio.com/public/_build/results?buildId=57950&view=logs&jobId=60ad5fa3-9ee1-561c-fc1d-1349a7b472eb&taskId=71e748b8-0ded-5502-f62f-08e9d9d9dfd7&lineStart=697&lineEnd=698&colStart=1&colEnd=1

IIS is still using package references. @natemcmaster would he need to check in and then update the IIS packages in the next build?

2018-12-13 23:36 UTC, natemcmaster commented
We are close to getting IIS onto project ref, so I would be okay ignoring the IIS test failures for a day. Okay with you @pakrym ?

2018-12-13 23:43 UTC, pakrym commented
As long as we don't forget about them I'm fine.

2018-12-13 23:54 UTC, HaoK commented
I'm happy to wait to merge next week as well, whatever is easiest for you guys is fine, this PR is done at this point so I can wait to merge when convenient

2019-01-09 19:58 UTC, davidfowl commented
@HaoK my bad bro, I broke all of your stuff

2019-01-09 22:30 UTC, HaoK commented
All good, rebased against master, will try to merge today if the checks pass

2019-01-09 23:30 UTC, HaoK commented
Wow checks all passed after rebasing and resolving conflicts, so safe to click the green button here @natemcmaster @Tratcher ?

2019-01-09 23:31 UTC, davidfowl approved these changes
Wow green! LGTM

2019-01-09 23:32 UTC, Tratcher commented
Yup, go for it.

2019-01-09 23:56 UTC, merged