Fix up how OIDC errors flow
dotnet/aspnetcore pull request #4520
Opened 2018-12-07 23:20 UTC by Tratcher

#4384 @PinpointTownes 
This tweaks the new AccessDenied feature (aspnet/Security#1887) to avoid changing the error and losing fidelity for the OIDC scenario.

2018-12-07 23:35 UTC, HaoK requested changes
Can we add some basic tests, this already regressed once.

2018-12-07 23:41 UTC, Tratcher commented
We don't even have the infrastructure set up yet... https://github.com/aspnet/Security/issues/772

I'd like to test it with the template test that caught the regression but I think we'd have to check in for that to run.

2018-12-07 23:45 UTC, PinpointTownes commented
> #4384 @PinpointTownes
This tweaks the new AccessDenied feature (aspnet/Security#1887) to avoid changing the error and losing fidelity for the OIDC scenario.

Interesting case (that I had obviously not taken into account :smile:)

I guess what you have now is fine, but I'm tempted to think it would be a good idea to also fix the B2C code to use the new event (instead of determining whether the exception message of `OpenIdConnectProtocolException` contains a magical code, which really looks weird).

2018-12-07 23:51 UTC, Tratcher commented
Yes B2C could use the new AccessDenied event, but it would still end up checking for a specific error code associated with password resets.

2018-12-08 00:35 UTC, HaoK commented
I think this should drive adding the infrastructure to at least add a test for this regression

2019-01-15 19:37 UTC, Tratcher commented
@HaoK let's merge this to unblock preview2.

2019-01-15 19:43 UTC, HaoK commented
Well constantly punting on test coverage in OIDC is what got us to this place, can't you just add something basic at least for the regression flow?

2019-01-15 19:44 UTC, HaoK commented
How can we even be sure this fixes the issue for example with no tests?

2019-01-15 23:41 UTC, Tratcher commented
I did find some tests for this scenario here: https://github.com/aspnet/AspNetCore/blob/c7d63649005c4c2863b34794994eef57595e7bb7/src/AADIntegration/test/Microsoft.AspNetCore.Authentication.AzureADB2C.UI.Test/AzureAdB2COpenIDConnectEventHandlersTests.cs#L99-L113

They hadn't failed because they were mocking the RemoteFailureContext. Since B2C is relying on specific types and strings I would only expect a behavior change like this to be caught by a functional test in B2C. I'll try writing one there.

2019-01-15 23:45 UTC, HaoK commented
Sounds good to me, yeah just one regression test in the b2c stuff as part of this PR to show that we fixed something and will catch at least this regression in the future works

2019-01-16 00:33 UTC, Tratcher commented
Updated

2019-01-16 03:04 UTC, HaoK approved these changes

2019-01-16 04:59 UTC, merged