Make security project ref
dotnet/aspnetcore pull request #4618
Opened 2018-12-12 22:00 UTC by jkotalik

2018-12-13 17:42 UTC, natemcmaster requested changes
A good start. I added a few comments about little things that can change in the project file, and I pushed a commit to your PR to trim some stale content from the README in src/Security

One thing you should for sure revert is the removal of the git submodules. :) Still required for now.

cc @Tratcher - you may be interested in viewing the source code layout.

2018-12-13 17:42 UTC, natemcmaster commented on src/Mvc/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Microsoft.AspNetCore.Mvc.ViewFeatures.csproj
> +    <Compile Include="$(RepositoryRoot)src\Shared\ChunkingCookieManager\**\*.cs" />
```suggestion
    <Compile Include="$(MSBuildThisFileDirectory)..\..\..\Shared\ChunkingCookieManager\**\*.cs" />
```

Until MVC converts to the new ref style, RepositoryRoot will point to src/Mvc/

2018-12-13 17:42 UTC, natemcmaster commented on src/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj
> +    <Compile Include="$(RepositoryRoot)src\Shared\ChunkingCookieManager\**\*.cs" />
Same here.

2018-12-13 17:42 UTC, natemcmaster commented on src/Security/Authentication.Cookies/src/Microsoft.AspNetCore.Authentication.Cookies.csproj
> +    <Compile Include="$(RepositoryRoot)src\Shared\ChunkingCookieManager\**\*.cs" />
```suggestion
    <Compile Include="$(SharedSourceRoot)ChunkingCookieManager\**\*.cs" />
```

2018-12-13 17:42 UTC, natemcmaster commented on src/Security/Authentication.JwtBearer/src/Microsoft.AspNetCore.Authentication.JwtBearer.csproj
>    </ItemGroup>
Nit: you can condense item groups of the same time.

2018-12-13 17:42 UTC, natemcmaster commented on src/Security/Authentication.WsFederation/samples/WsFedSample/WsFedSample.csproj
> +    <TargetFrameworks>net461;netcoreapp2.0</TargetFrameworks>
```suggestion
    <TargetFrameworks>net461;netcoreapp2.1</TargetFrameworks>
```

Might have originally been 2.0, but let's cleanup as long as we're here :)

2018-12-13 17:42 UTC, natemcmaster commented on src/Security/Authentication/src/Microsoft.AspNetCore.Authentication.csproj
> +    <PackageReference Include="Microsoft.Extensions.SecurityHelper.Sources" PrivateAssets="All" Version="$(MicrosoftExtensionsSecurityHelperSourcesPackageVersion)" />
```suggestion
    <Reference Include="Microsoft.Extensions.SecurityHelper.Sources" PrivateAssets="All" />
```

2018-12-13 17:42 UTC, natemcmaster commented on src/Security/Authorization.Policy/src/Microsoft.AspNetCore.Authorization.Policy.csproj
>      <PackageReference Include="Microsoft.Extensions.SecurityHelper.Sources" PrivateAssets="All" Version="$(MicrosoftExtensionsSecurityHelperSourcesPackageVersion)" />
```suggestion
    <Reference Include="Microsoft.Extensions.SecurityHelper.Sources" PrivateAssets="All" />
```

2018-12-13 17:42 UTC, natemcmaster commented on src/Security/CookiePolicy/test/Microsoft.AspNetCore.CookiePolicy.Test.csproj
> +    <Compile Include="$(RepositoryRoot)src\Shared\ChunkingCookieManager\**\*.cs" />
```suggestion
    <Compile Include="$(SharedSourceRoot)ChunkingCookieManager\**\*.cs" />
```

2018-12-14 18:04 UTC, Tratcher commented
The layout's a little odd, especially for the AuthN samples and tests that pull in stuff from other folders. How about:
- Authentication/
  - src
    - Core
    - Cookies
    - Facebook
    - Google
    - JwtBearer
    - ...
  - samples/SocialSample 
  - tests
- Authorization/
  - src
    - Core (src, test)
    - Policy
- CookiePolicy
- Interop

Also, the src folder can be flattened when it's the only folder for a given package. E.g. `Authenticaiton/Facebook/Microsoft.AspnetCore.Authentication.Facebook.csproj`

2018-12-14 18:11 UTC, JunTaoLuo commented
I'll take over this PR since I need it for Identity.

2018-12-14 19:30 UTC, Tratcher commented
Updated after talking to @natemcmaster 

- Authentication/
  - Core
  - Cookies
  - Facebook
  - Google
  - JwtBearer
  - ...
  - samples/SocialSample 
  - tests
- Authorization/
  - Core
  - Policy
- CookiePolicy
- Interop

And don't worry about flattening the solo src dirs, it sounds like each of these will get paired with a ref dir.

2018-12-14 20:55 UTC, JunTaoLuo commented
Updated

2018-12-14 21:57 UTC, Tratcher approved these changes

2018-12-14 22:40 UTC, JunTaoLuo approved these changes

2018-12-14 22:48 UTC, natemcmaster approved these changes

2018-12-14 22:49 UTC, merged