Reset ConnectProtocol during reset
dotnet/aspnetcore pull request #47660
Opened 2023-04-12 01:09 UTC by adityamandaleeka

Fixes https://github.com/dotnet/aspnetcore/issues/47647

cc @Tratcher @MihaZupan 

We don't seem to have any tests for this type of thing, and from looking at the H2 WS tests I wasn't sure if there's even a good way to add one given how those tests work. Any thoughts @Tratcher?

2023-04-12 16:18 UTC, MihaZupan approved these changes

2023-04-12 16:26 UTC, Tratcher approved these changes

2023-04-12 17:36 UTC, Tratcher commented
There should be tests about caching and re-use, I wonder if those cover reset. I'll try to find one.

2023-04-12 17:39 UTC, Tratcher commented
https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs#L307

2023-04-13 01:02 UTC, JamesNK requested changes
LGTM but need test

2023-04-19 23:03 UTC, JamesNK approved these changes

2023-04-19 23:52 UTC, merged