Switch to bootstrap icons
dotnet/aspnetcore pull request #48652
Opened 2023-06-07 15:58 UTC by surayya-MS

# Switch to bootstrap icons

Part of https://github.com/dotnet/aspnetcore/issues/48341
Before:
![open-iconic-before](https://github.com/dotnet/aspnetcore/assets/114938397/02d9d46c-bbf4-4be8-b354-7f5388d53722)
After:
![after](https://github.com/dotnet/aspnetcore/assets/114938397/9a25d2a7-9d12-43ed-84ac-60ff7120a98f)

2023-06-07 17:10 UTC, javiercn approved these changes

2023-06-07 17:52 UTC, Eilon requested changes
Also wondering in general if there are any notable visual differences between the old and new icons?

2023-06-08 09:07 UTC, SteveSandersonMS commented
> Also wondering in general if there are any notable visual differences between the old and new icons?

I assume the new icons are not identical but from the naming it sounds like @surayya-MS has chosen ones similar to the old ones, which sounds ideal to me. I'd be interested to see a screenshot of the result though!

2023-06-08 09:31 UTC, surayya-MS commented
@SteveSandersonMS , @Eilon I attached the screenshots to the description

2023-06-08 10:28 UTC, SteveSandersonMS commented
Looks great! Definitely better than the old icons.

2023-06-08 14:37 UTC, surayya-MS commented on src/Components/Samples/BlazorServerApp/Pages/_Layout.cshtml
> +    <link rel="stylesheet" href="css/bootstrap-icons/bootstrap-icons.css" />
Done

2023-06-08 16:51 UTC, Eilon commented
> @SteveSandersonMS , @Eilon I attached the screenshots to the description. I tried to choose similar ones https://icons.getbootstrap.com/

Yeah looks good! I wasn't expecting identical, I just wasn't sure if they were conceptually different. Nice!

2023-06-08 16:59 UTC, Eilon requested changes, later dismissed
Got another fun one: I think we need to update the appropriate Third Party Notices (3PN) text files to reflect this change as well. The notices file lists the various projects and licenses of other things that we either include in this repo, or re-ship to users (e.g. stuff that's in templates).

1. The Bootstrap stuff that we currently list might be out of date (?)
2. The Bootstrap Icons stuff seems like it's a separate project, and we would need to add it.

There are two 3PN files that I think might need to be updated:
1. https://github.com/dotnet/aspnetcore/blob/main/THIRD-PARTY-NOTICES.txt --> this should list every project/license that is checked into this repo, regardless of why we include it
2. https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/THIRD-PARTY-NOTICES --> this should list every project/license that is part of the templates that we ship to users

Having said all of this, it is probably best to confirm with this repo's owners to verify what process should be used for this.

2023-06-09 08:57 UTC, surayya-MS commented
@Eilon I'm not sure where I could get the license for bootstrap icons and where to include it. @SteveSandersonMS , @javiercn , @danroth27 do you know?

My findings so far:

- open iconic wasn't included in these 2 files https://github.com/dotnet/aspnetcore/blob/main/THIRD-PARTY-NOTICES.txt and https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/THIRD-PARTY-NOTICES
- open iconic however has this license inside its folder https://github.com/dotnet/aspnetcore/blob/6575b289081b9f85fb30d01c7b306d1ec5d00a68/src/Components/Samples/BlazorServerApp/wwwroot/css/open-iconic/ICON-LICENSE
- Bootstrap license is included in one of the mentioned files https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/THIRD-PARTY-NOTICES
- There is a license file inside `Source code zip`. It can be downloaded [here](https://github.com/twbs/icons/releases/tag/v1.10.5). But I'm not sure if this is the right one for bootstrap icons because the icons are in the bootstrap-icons-1.10.5.zip and there wasn't any license file, only some comments about license and copyright in bootstrap-icons.css and min.css (see in this PR)
- https://getbootstrap.com/docs/4.0/about/license/ here it says "Keep the license and copyright notice included in Bootstrap’s CSS and JavaScript files when you use them in your works"

2023-06-09 22:32 UTC, Eilon commented
> @javiercn, @Eilon should I also switch to bootstrap icons in maui blazor template?

Yeah perhaps log a bug in dotnet/maui for now, and link to the AspNetCore issue/PR.

2023-06-09 22:36 UTC, Eilon commented
> @Eilon I'm not sure where I could get the license for bootstrap icons and where to include it. @SteveSandersonMS , @javiercn , @danroth27, @mkArtakMSFT do you know?
> 
> My findings so far:
> 
> * open iconic wasn't included in these 2 files https://github.com/dotnet/aspnetcore/blob/main/THIRD-PARTY-NOTICES.txt and https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/THIRD-PARTY-NOTICES

It probably _should_ have been, but too late now.

> * open iconic however has this license inside its folder https://github.com/dotnet/aspnetcore/blob/6575b289081b9f85fb30d01c7b306d1ec5d00a68/src/Components/Samples/BlazorServerApp/wwwroot/css/open-iconic/ICON-LICENSE

Yeah we preserve the OSS stuff as-is, including any license files they already have.

> * Bootstrap license is included in one of the mentioned files https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/THIRD-PARTY-NOTICES

That's good. Does it match the version that we use?

> * There is a license file inside `Source code zip`. It can be downloaded [here](https://github.com/twbs/icons/releases/tag/v1.10.5). But I'm not sure if this is the right one for bootstrap icons because the icons are in the bootstrap-icons-1.10.5.zip and there wasn't any license file, only some comments about license and copyright in bootstrap-icons.css and min.css (see in this PR)
> * https://getbootstrap.com/docs/4.0/about/license/ here it says "Keep the license and copyright notice included in Bootstrap’s CSS and JavaScript files when you use them in your works"

The `wwwroot/css/bootstrap-icons/bootstrap-icons[.min].css` files in this PR say `Licensed under MIT (https://github.com/twbs/icons/blob/main/LICENSE)`, so I would personally go as far as to mention that we use `Bootstrap Icons v1.10.5` and copy the license text of https://github.com/twbs/icons/blob/main/LICENSE as the entry for it in the 3rd party notices. In my view it's two projects (Bootstrap, and Bootstrap Icons), that happen to use the same license.

But........ please confirm with someone who has more authority in this repo 😄 Back in my day in this repo, that's what I would have done.

2023-06-12 13:53 UTC, surayya-MS commented
Thanks @Eilon!

I added the license for Bootstrap icons.

Bootstrap was updated to 5.1.0 https://github.com/dotnet/aspnetcore/pull/35197. I now updated the 3PN too

2023-06-12 14:42 UTC, SteveSandersonMS approved these changes
Superb! This looks ideal.

2023-06-13 15:42 UTC, mkArtakMSFT commented
I'm dismissing @Eilon's "requested changes" now given he is away. Looks like @surayya-MS has done all that is needed for now!

2023-06-13 15:43 UTC, merged