Add EditContext.IsValid(..) to determine if a field has any associated validation messages
dotnet/aspnetcore pull request #48698
Opened 2023-06-10 02:47 UTC by ElderJames

# Add EditContext.IsValid(..) to determine if a field has any associated validation messages

- [ ] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Implement the `EditContext.IsValid(FieldIdentifier fieldIdentifier)` API.

Fixes #31252

2023-06-20 15:25 UTC, mkArtakMSFT commented
@SteveSandersonMS can you please review this? Thanks!

2023-08-11 18:23 UTC, mkArtakMSFT requested changes
Thanks for your PR, @ElderJames.
The APIs you've added look good. Could you please also include tests for these new APIs in https://github.com/dotnet/aspnetcore/blob/main/src/Components/Forms/test/EditContextTest.cs?

2023-08-13 13:56 UTC, ElderJames commented
@mkArtakMSFT I have added the test for that, thank you!

2023-08-14 00:16 UTC, mkArtakMSFT approved these changes

2023-08-14 00:17 UTC, merged