[skip-ci] Add missing xml docs for ExceptionHandler
dotnet/aspnetcore pull request #48814
Opened 2023-06-14 17:21 UTC by divyeshio

## Description

Adds missing inline xml docs for IExceptionHandler and AddExceptionHandler method

Fixes #48640

2023-06-14 18:10 UTC, amcasey approved these changes

2023-06-14 22:19 UTC, adityamandaleeka commented on src/Middleware/Diagnostics/src/ExceptionHandler/IExceptionHandler.cs
>  public interface IExceptionHandler
`TryHandleAsync` below also needs to be filled in.

2023-06-14 22:20 UTC, adityamandaleeka commented on src/Middleware/Diagnostics/src/ExceptionHandler/IExceptionHandler.cs
>  public interface IExceptionHandler
Other than that, this looks good to me. Thanks for doing it.

2023-06-15 02:07 UTC, JamesNK requested changes, later dismissed

2023-06-15 02:07 UTC, JamesNK commented on src/Middleware/Diagnostics/src/ExceptionHandler/IExceptionHandler.cs
> +/// different scenarios in the application.
```suggestion
/// Represents an interface for handling exceptions in ASP.NET Core applications.
/// `IExceptionHandler` implementations are used by the exception handler middleware.
```

2023-06-23 23:43 UTC, Tratcher approved these changes
Thanks

2023-06-26 17:55 UTC, merged