Remove ApiAuthorization.IdentityServer
dotnet/aspnetcore pull request #49193
Opened 2023-07-04 01:19 UTC by halter73

Remove Microsoft.AspNetCore.ApiAuthorization.IdentityServer and

2023-07-07 18:04 UTC, wtgodbe commented on .config/CredScanSuppressions.json
> -    {
Thanks for catching these 🥳

2023-07-07 18:05 UTC, wtgodbe commented on eng/Baseline.xml
> -  <Package Id="Microsoft.AspNetCore.ApiAuthorization.IdentityServer" Version="6.0.0" />
Undo this, the baseline lists previously released packages, not the current set

2023-07-07 18:06 UTC, wtgodbe commented on eng/scripts/CodeCheck.ps1
> +                    if (!$file.Contains('DevServer/src/PublicAPI.Shipped.txt') -and !$file.Contains('ApiAuthorization.IdentityServer/src/PublicAPI.Shipped.txt')) {
Remove this, I'll just merge on red

2023-07-07 18:07 UTC, wtgodbe requested changes
Couple small changes + undo the submodule change

2023-07-10 16:06 UTC, halter73 commented
@wtgodbe Is this good to merge?

2023-07-10 17:16 UTC, wtgodbe approved these changes

2023-07-10 17:17 UTC, merged