Fix script tag insertion in DomMerging
dotnet/aspnetcore pull request #51184
Opened 2023-10-06 09:45 UTC by BarkovskiyMaxim

# Fix script tag insertion in DomMerging

- [ ] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}

Fixes https://github.com/dotnet/aspnetcore/issues/51175

2023-10-06 10:44 UTC, SteveSandersonMS commented
Thanks for proposing this.

I think we already have an equivalent fix in https://github.com/dotnet/aspnetcore/pull/51059/commits/18edeaaeae76ebe7eb9351aabf24dfe1771adc71 which is still pending merge. The approach used there is similar to what you've done, except the `script` elem is replaced earlier in the process (immediately after parsing, instead of at the point of insertion). Overall I think the effect will be the same.

Please have a look and let us know if you have concerns. If you agree the approach used in #51059 meets your needs then this PR could be closed.

2023-10-06 10:48 UTC, SteveSandersonMS commented
Actually no, I think I was wrong. The fix we've applied in https://github.com/dotnet/aspnetcore/pull/51059 will only apply to interactive rendering. It won't apply to content being inserted during enhanced nav, which is the scenario you're addressing.

So, what you've done in this PR is reasonable and I think we would accept the fix, however it would need to come with an E2E test. Is that something you'd be open to adding?

2023-10-06 10:51 UTC, SteveSandersonMS commented
That said, this whole thing is very dubious. This means that as the user navigates around the site, the same `<script>` make keep re-running within the page as it keeps getting removed and re-added. In a lot of cases, this will lead to errors or obscure bugs with things being double-registered.

I'm not actually certain we want to support this pattern as people are really going to get into trouble with it. @dotnet/aspnet-blazor-eng  we should discuss whether it's desirable to support this or not.

2023-10-06 12:42 UTC, javiercn commented
I am not sure that we should do this, I am very inclined to say no:
* First, from all the things @SteveSandersonMS mentioned.
* Second, I am not sure about the impact on CSP compliance (meaning, if this precludes people from using CSP).
* Third, I do not think injecting `script` tags will work well with this model.
  * There might be alternative approaches that work better, like hooking up to the enhanced navigation event and triggering the import of some JS module + triggering some action tied to the current page with later cleanup.

In general, anything that relies on global state is going to be problematic with enhanced navigation, as it breaks the assumption that things are going to execute once when the document loads and automatically cleanup upon the next navigation.

The app needs to account for this and design around it if wants to use enhanced navigation.

2023-10-06 14:30 UTC, BarkovskiyMaxim commented
@SteveSandersonMS  I'm ready to write a test, but we need to make a decision. I agree that multiple script loading can potentially cause issues. However, if we make such a solution optional (for example, by marking the script with a specific attribute), it could be viable. An alternative option is to restrict this mode to work exclusively with scripts without content. In that case, we can cache which src scripts have already been loaded and avoid creating a new element if it's in the cache. 

@javiercn Regarding CSP, I don't see any issues there; it all depends on the script-src directive.

2023-10-06 14:49 UTC, BarkovskiyMaxim commented
The solution might look something like this:

~~~ts
  const isScriptModuleNode = (node: Node): node is HTMLScriptElement => {
    return ((node: Node): node is HTMLScriptElement => {
      return node.nodeName.toLowerCase() === 'script';
    })(node) && node.hasAttribute('type') && node.getAttribute('type') === 'module';
  }

  if(isScriptModuleNode(nodeToInsert)) {
    const scriptNode = document.createElement('script');
    Array.from(nodeToInsert.attributes).forEach(attribute => {
      scriptNode.setAttribute(
        attribute.nodeName,
        attribute.nodeValue as string,
      );
    });
    nodeToInsert = scriptNode;
  }
~~~

2023-10-09 07:21 UTC, BarkovskiyMaxim commented
@dotnet-policy-service agree

2023-11-15 13:22 UTC, FirdavsAsadov requested changes
An alternative is to restrict this mode to only work with content-free scripts. In this case, we can cache which src scripts are already loaded and restrict the creation of a new element if it is already in the cache

2025-01-24 15:35 UTC, javiercn commented
I think we need a more complete solution here than just supporting module scripts.

I think it's important for us to not only add the ability to bring in a module, but to have the ability for a module to receive a callback during navigations, otherwise the behavior will be surprising to many people (first time some logic gets triggered, but after the next navigation nothing happens).

A basic example is a script that hooks on client-side form validation. Even if it's a module, if it's not designed to react on page navigations it will not hook on to new forms after an enhanced nav.

2025-01-24 15:36 UTC, closed without merging