[WIP] Add health checks routing extensions
dotnet/aspnetcore pull request #5127
Opened 2018-12-15 06:40 UTC by JamesNK

TODO:

- [ ] Support port?
- [ ] Docs

Fixes https://github.com/aspnet/AspNetCore/issues/4617

2018-12-15 06:44 UTC, JamesNK commented
@rynowak UseHealthChecks supports limiting access to a port. What do you think of making the `DomainMatcherPolicy` that I wrote ship in routing? Then it would be a simple matter of setting the appropriate metadata in for the healthchecks endpoint.

2018-12-18 16:35 UTC, rynowak commented on src/Middleware/HealthChecks/src/Builder/HealthCheckEndpointRouteBuilderExtensions.cs
> +namespace Microsoft.AspNetCore.Diagnostics.HealthChecks.Builder
This should be `Microsoft.AspNetCore.Builder`

2018-12-18 22:17 UTC, rynowak commented on src/Middleware/HealthChecks/src/Builder/HealthCheckEndpointRouteBuilderExtensions.cs
> +    public static class HealthCheckEndpointRouteBuilderExtensions
docccs

2018-12-18 22:18 UTC, rynowak commented
As discussed we want support for filtering on host/port, I'm ok with that to land separately.

2018-12-18 22:18 UTC, rynowak requested changes
Seems good. Need to get final polish

2018-12-18 22:35 UTC, JamesNK commented
re: host/port

UseMiddleware has port as an argument. Do you have a strong preference on whether MapHealthChecks should have an overload that takes a port and adds the metadata for you, or do we tell people to use a standard extension method to add port metadata.

I lean towards and extension method but I don't have a strong preference either way.

2018-12-19 00:21 UTC, rynowak commented
I lean towards extension method as well if it's easy to use. If not we can add it back as first-class, so lets start with the extension method

2018-12-20 20:37 UTC, rynowak approved these changes

2018-12-20 22:18 UTC, merged