Set IExceptionHandlerFeature on DeveloperExceptionPageMiddleware
dotnet/aspnetcore pull request #52688
Opened 2023-12-09 17:11 UTC by Kahbazi

Fixes https://github.com/dotnet/aspnetcore/issues/49195

2023-12-11 17:42 UTC, BrennanConroy commented on src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs
>                  await _exceptionHandler(new ErrorContext(context, ex));
nit: Move `new ErrorContext(...)` into a local and call `SetExceptionHandlerFeatures`

2023-12-12 16:38 UTC, BrennanConroy commented on src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs
>                  await _exceptionHandler(new ErrorContext(context, ex));
There is a `SetExceptionHandlerFeatures` method already.
https://github.com/dotnet/aspnetcore/blob/1a3fda55135cfdb0f81da8c51e3272902103ea4b/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs#L84
You can call it if you just move `new ErrorContext` into a local.
```
var ec = new ErrorContext(context, ex);
SetExceptionHandlerFeatures(ex);
await _exceptionHandler(ec);
```

2023-12-18 17:43 UTC, BrennanConroy approved these changes

2023-12-18 23:24 UTC, JamesNK requested changes, later dismissed

2023-12-18 23:24 UTC, JamesNK commented on src/Middleware/Diagnostics/test/UnitTests/ExceptionHandlerMiddlewareTest.cs
> +        var response = await server.CreateClient().SendAsync(request);
This test isn't forcing the asserts to run. Move asserts into the main path of the test:

```suggestion
        // Arrange
        var tcs = new TaskCompletionSource<IExceptionHandlerPathFeature>(TaskCreationOptions.RunContinuationsAsynchronously);

        using var host = new HostBuilder()
            .ConfigureWebHost(webHostBuilder =>
            {
                webHostBuilder
                .UseTestServer()
                .Configure(app =>
                {
                    app.Use(async (context, next) =>
                    {
                        await next();
                        
                        var exceptionHandlerFeature = context.Features.GetRequiredFeature<IExceptionHandlerPathFeature>();
                        tcs.SetResult(exceptionHandlerFeature);
                    });
                    app.UseExceptionHandler(exceptionApp =>
                    {
                        exceptionApp.Run(context => Task.CompletedTask);
                    });
                    app.Run(context =>
                    {
                        throw new Exception("Test exception");
                    });

                });
            }).Build();

        await host.StartAsync();

        var server = host.GetTestServer();
        var request = new HttpRequestMessage(HttpMethod.Get, "/path");

        var response = await server.CreateClient().SendAsync(request);

        var feature = await tcs.Task;
        Assert.NotNull(feature);
        Assert.Equal("Test exception", feature.Error.Message);
        Assert.Equal(context.Request.Path, feature.Path);
```

(note: changed in a text field, not might not compile, and/or have bugs)

2024-06-21 21:39 UTC, adityamandaleeka commented
@Kahbazi Are you still interested in working on this?

2024-06-24 12:32 UTC, Kahbazi commented
@adityamandaleeka Sorry I missed this PR, I will work on it this weekend.

2025-12-10 07:05 UTC, merged