#51611 - Extended Blazor server and webassembly options to match web format.
dotnet/aspnetcore pull request #54649
Opened 2024-03-20 18:12 UTC by khamzakhamzakhamza

[#51611](https://github.com/dotnet/aspnetcore/issues/51611) - Extended Blazor server and webassembly options to match web format.

Extends options consumed by the ```Blazor.start()``` method in ```blazor.server.js``` and ```blazor.webassembly.js``` to match how they work in ```blazor.web.js``` and in the documentation.

## Description
I followed the [design](https://github.com/dotnet/aspnetcore/issues/51611#issuecomment-1866955885) proposed by @MackinnonBuck and implemented the suggested changes. I have tested changes locally and everything works as expected. 

I couldn't find any unit or integration tests for the Boot classes and felt hesitant to create new ones. However, I am happy to do so if someone from the team decides they are needed.

2024-03-20 18:14 UTC, khamzakhamzakhamza commented
> @khamzakhamzakhamza please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

2024-12-12 21:53 UTC, MackinnonBuck approved these changes

2024-12-12 21:53 UTC, MackinnonBuck commented
/azp run

2024-12-12 22:12 UTC, MackinnonBuck requested changes
Sorry to revoke the approval, but we'll likely need tests to ensure that this doesn't break in the future. E2E tests are probably the easiest way to test this (rather than trying to test the `Boot.*.ts` code directly.

2024-12-12 22:17 UTC, MackinnonBuck commented
Related to https://github.com/dotnet/aspnetcore/pull/56758. We'd only want to take one of these changes, as they do the same thing.

2025-02-03 11:16 UTC, maraf commented
@khamzakhamzakhamza Thank you for your contribution and sorry for a late reply.

We need some automated tests validating that options are correctly propagated. The easiest way to achieve it is through E2E test. There are tests that contains some startup options and we need to modify them to run once with wasm/server options as they do now and second with options matching web format. For WebAssembly such test candidate might be https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/WebAssemblyConfigureRuntimeTest.cs#L33 that is running https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/wwwroot/index.html#L66-L70. For Server we probably need to create a new test

2025-02-07 19:18 UTC, guardrex commented
@maraf ... It looks like this won't make Preview 1. I have the [docs PR (`dotnet/AspNetCore.Docs` #34660)](https://github.com/dotnet/AspNetCore.Docs/pull/34660) ready to merge whenever this reaches a preview release.

2025-02-26 14:17 UTC, guardrex commented
@maraf @javiercn ... *DAH!* 😄 ... I have the [docs PR (`dotnet/AspNetCore.Docs` #34660)](https://github.com/dotnet/AspNetCore.Docs/pull/34660) set up to react to this. I'm 🤞🍀 that this can make .NET 10 so that my work doesn't go to waste.

2025-03-02 18:56 UTC, closed without merging

2025-03-03 16:54 UTC, guardrex commented
@lewing ... This closed again. Let me know if it's going to be dropped ... I'll close the docs PR if that happens.