Updated naming pattern used the  s_ prefix for private static fields
dotnet/aspnetcore pull request #56647
Opened 2024-07-05 13:46 UTC by siyandand1

Title: Enforce Consistent Naming for Private Static Fields

Description:

The dotnet/aspnetcore repository currently mixes _underscore and PascalCase naming conventions for private static fields. To ensure code consistency and readability, we should adopt a single naming convention. Given that dotnet/runtime uses the s_ prefix for private static fields, I propose we align with this convention.

Changes Proposed:

    Update private static fields to use the s_ prefix consistently.
    Introduce a naming rule in the .editorconfig file to enforce this convention.

Rationale:

Consistency in naming conventions helps maintain readable and maintainable code. By aligning with the dotnet/runtime convention, we ensure uniformity across the broader .NET ecosystem.

Changes Made:

    Renamed private static fields to use the s_ prefix.
    Added a naming rule to the .editorconfig file to enforce the s_ prefix for private static fields.

2024-07-05 14:03 UTC, javiercn commented
@siyandand1 thanks for contacting us.

This PR doesn't seem to have any issue associated with it. Please file an issue and start the discussion in the issue before making any changes. We aren't going to take changes like this without a discussion and without the team agreeing that this is the right thing to do and important to do moving forwards.

2024-07-05 14:20 UTC, siyandand1 commented
Apologies with the Confusion: The issue being addressed was: https://github.com/dotnet/aspnetcore/issues/50888

2024-07-05 16:48 UTC, mkArtakMSFT commented
@JamesNK can you please review this? Thanks!

2024-07-05 16:49 UTC, javiercn commented
@mkArtakMSFT before any review happens, I think this needs discussion with the broader team.

2024-07-08 13:30 UTC, javiercn commented
@mitchdenny I think this is a style option and we shouldn't be imposing a convention without broader discussion across the team. (Maybe through email or DoI (@wtgodbe)). 

This is not a convention our team follows, and I think that's fine. It's weird that we would choose to adopt something like `s_` for static fields and not `m_` for member fields, and IMO it just brings another set of inconsistencies to the table.

Our convention is essentially `_` for fields of the class that are not used/visible outside the class hierarchy, I don't see how we benefit from prefixing them with `s`, it just seems that it leaves us in no man's land, where we mix the two popular conventions and don't fully apply neither of. (and I'm not advocating for prefixing all members `m_`).

I don't want to turn this into a discussion, but I think it deserves more talking before we go in one direction as this break's years of muscle memory and doesn't offer any benefit beyond what `_` already provides (which is scoping the results quickly for intellisense).

2024-07-08 14:53 UTC, captainsafia commented
My two cents: I think resolving the inconsistency between PascalCase and underscore case for private static fields in the codebase is a net good. In that case, I would propose moving from PascalCase for some fields to underscore case for all fields. IMO, that solves the immediate problem of inconsistency between the two and avoids introducing a new set of issues (around member and static fields, like @javiercn mentioned above).

With that being said, it would be good to evaluate the size of the code delta associated with this change. As @mitchdenny mentioned, it'll introduce a pain around backporting. Also, I'm cautious about merging this change during the preview7/RC1 timelines which tend to be high traffic with respect to merged PRs and having to solve merge conflicts related to the rename might prove tedious.

2024-07-09 00:44 UTC, JamesNK commented
This change (approx 400 lines) isn't large. I don't think complicating backports should be a concern. And this change is minor compared to adding nullable annotations everywhere or switching to file scoped namespaces.

@javiercn In case you missed it, I started an informal poll in the aspnetcore team chat.

2024-07-12 08:04 UTC, JamesNK requested changes

2024-07-12 08:04 UTC, JamesNK commented on src/Components/Shared/src/ElementReferenceJsonConverter.cs
> +    private static readonly JsonEncodedText s_IdProperty = JsonEncodedText.Encode("__internalId");
This should be `s_idProperty`. The character after the first underscore should be lower case.

Applies to all fields.

2024-07-12 08:06 UTC, JamesNK commented
Can you add this to the .editorconfig file in the root of the respoitory:

https://github.com/dotnet/aspire/blob/cf61a58a739f059469bcbfbff7d5121526f6fa88/.editorconfig#L67-L75

To the .editorconfig file in the root of the respoitory:

https://github.com/dotnet/aspnetcore/blob/7498cea189f5e32a11ef480729384ff6b5dc662f/.editorconfig

Try to be consistent with the location so the editorconfigs are similar.

2024-12-13 23:17 UTC, mkArtakMSFT commented
Closing, as there has been no response from the author for a while.

2024-12-13 23:17 UTC, closed without merging