Parse enum unions in config
dotnet/aspnetcore pull request #58328
Opened 2024-10-09 20:15 UTC by amcasey

In particular, `HttpProtocols` and `SslProtocols`.  This should be more forward compatible than adding an explicit enum member for each combination of values.

For #58088

2024-10-09 23:16 UTC, JamesNK commented
Parsing with commas is automatically supported by enum parse. Could that be used?
```cs
string input = "Read, Write";
Permissions userPermissions = (Permissions) Enum.Parse(typeof(Permissions), input);
Console.WriteLine(userPermissions); // Output: Read, Write
```
Having `|` delimited enum values is different from the default comma separated.

2024-10-09 23:17 UTC, BrennanConroy approved these changes

2024-10-09 23:26 UTC, JamesNK requested changes

2024-10-09 23:26 UTC, JamesNK commented on src/Servers/Kestrel/Core/src/Internal/ConfigurationReader.cs
> +            var split = protocols.Split('|');
`Enum.TryParse` can already parse multiple values. Why not use that?

2024-10-14 17:58 UTC, amcasey commented
I had no idea it would do that.  Apparently, neither did the user who prompted the PR.  I'll ping them and see if commas are satisfactory.

2025-01-22 01:50 UTC, lewing commented
It looks like this can be safely closed now?

2025-01-22 02:10 UTC, closed without merging