Migrate off of Debian 11
dotnet/aspnetcore pull request #59584
Opened 2024-12-20 08:44 UTC by v-firzha

aspnetcore references a Debian 11 image that is EOL (see https://github.com/dotnet/core/issues/9625):
https://github.com/dotnet/aspnetcore/blob/dc3b2086feef8e62771254fdfded9d9d8a05346f/eng/targets/Helix.Common.props#L6

Update Debian11 -> 12

2024-12-20 13:30 UTC, mthalman approved these changes

2024-12-20 17:32 UTC, wtgodbe requested changes

2024-12-20 17:32 UTC, wtgodbe commented on eng/targets/Helix.Common.props
> +    <HelixQueueDebian11>(Debian.12.Amd64.Open)Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-amd64</HelixQueueDebian11>
Please also change the property name to `HelixQueueDebian12` & replace all instances of it in the repo

2025-01-07 22:14 UTC, wtgodbe approved these changes

2025-01-08 01:43 UTC, wtgodbe approved these changes

2025-01-08 01:44 UTC, merged