Simplify PublicTopLevelProgramGenerator
dotnet/aspnetcore pull request #59601
Opened 2024-12-22 11:57 UTC by Youssef1313

# {PR title}

- [ ] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}

Fixes #{bug number} (in this specific format)

2024-12-23 21:58 UTC, captainsafia reviewed
Thanks for opening this PR, @Youssef1313! It looks like there's some build errors that need to be resolved.

BTW, I recognize that multiple transformations aren't necessarily needed, but is there a harm to having them? Also in this case, I figured there might be some value to having some transformations (like the resolution of the syntax nodes) as the last stage in case other transformations fail.

2024-12-31 00:13 UTC, Youssef1313 commented
@captainsafia I think yes. It' likely better as a single step. This avoids caching symbols which will be not equatable anyways (not sure if it can cause leak or not though)

@CyrusNajmabadi will be better to advise.

2025-01-13 18:44 UTC, captainsafia approved these changes

2025-01-13 18:47 UTC, captainsafia commented
/azp run

2025-01-13 20:30 UTC, captainsafia requested changes
I hit approve too fast. It looks like this change introduced some test regressions.

2025-01-13 20:56 UTC, CyrusNajmabadi commented on src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs
> +            declaringSyntaxReferences.Single().GetSyntax(cancellationToken) is not ClassDeclarationSyntax
`DeclaratingSyntaxReferences: [var singleSyntaxReference] && ...

2025-01-13 20:57 UTC, CyrusNajmabadi approved these changes

2025-01-13 20:58 UTC, CyrusNajmabadi commented
> BTW, I recognize that multiple transformations aren't necessarily needed, but is there a harm to having them?

yes.  Each step is a new table in our pipeline that we have to compute and compare before/after.  Symbols in these steps are *particularly* bad as they will *always* compare false.  so it's just added cost (both memory and cpu) that *never* improves incrementality.

2025-01-15 13:08 UTC, Youssef1313 commented
@captainsafia This is hopefully good to merge if CI goes green.

2025-02-05 23:28 UTC, closed without merging