Fix #6102 - Intense CPU utilization on page change
dotnet/aspnetcore pull request #6542
Opened 2019-01-09 22:08 UTC by rynowak

The issue here was that every time a Razor Page changed, we would
subscribe an additional time to the endpoint change notifications. This
means that if you tweaked a page 30 times, we would update the address
table 31 times when you save the file. If you were doing a lot of editing
then this would grow to a really large amount of computation.

The fix is to use DataSourceDependentCache, which is an existing utility
type we developed for this purpose. I'm not sure why it wasn't being
used for this already. We're already using DataSourceDependentCache in a
bunch of other places, and it's well tested.

I also tweaked the stucture of this code to be more similar to
EndpointNameAddressScheme. This involved some test changes that all
seemed like good cleanup. The way this was being tested was a little
wonky.

2019-01-09 22:09 UTC, rynowak commented on src/Http/Routing/src/DataSourceDependentCache.cs
> +
I noticed this was missing while re-reviewing this code. It's worth adding because this could would nullref eventually during change token refresh.

2019-01-09 22:09 UTC, rynowak commented on src/Http/Routing/src/RouteValuesAddressScheme.cs
> +using System.Collections.Generic;
Thanks VS. It keeps changing my settings.

2019-01-09 22:28 UTC, JamesNK approved these changes

2019-01-09 22:30 UTC, rynowak commented on src/Http/Routing/test/UnitTests/RouteValuesAddressSchemeTest.cs
> +            var addressScheme = new RouteValuesAddressScheme(new CompositeEndpointDataSource(new[] { dynamicDataSource }));
Yes. notice that I added a bunch of verification that was missing.

2019-01-09 22:31 UTC, rynowak commented on src/Http/Routing/src/RouteValuesAddressScheme.cs
> +            }
This would cause a nullref a few lines down.

2019-01-09 23:35 UTC, davidfowl commented
Ah you’re not using the helper. I guess it’s ok because you never dispose the registration. Is there another leak there because of that?

2019-01-10 01:39 UTC, davidfowl commented on src/Http/Routing/src/RouteValuesAddressScheme.cs
>      internal class RouteValuesAddressScheme : IEndpointAddressScheme<RouteValuesAddress>
I would make this disposable and dispose the DataSourceDependentCache in Dispose.

2019-01-10 01:39 UTC, davidfowl requested changes
Make DataSourceDependentCache disposable and dispose it in the places that use it.

2019-01-10 03:04 UTC, davidfowl commented on src/Http/Routing/src/RouteValuesAddressScheme.cs
>      internal class RouteValuesAddressScheme : IEndpointAddressScheme<RouteValuesAddress>
Starting and stopping the host in process. We've already had an instance of an issue like this in options.

2019-01-14 02:07 UTC, rynowak commented
Updated. @davidfowl - do middleware get disposed? https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/EndpointRoutingMiddleware.cs#L64 will have a change token inside.

2019-01-14 02:15 UTC, davidfowl commented
> Updated. @davidfowl - do middleware get disposed? https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/EndpointRoutingMiddleware.cs#L64 will have a change token inside.

@rynowak Nope 😢. Can you move it into a service that is itself disposable?

2019-01-14 03:46 UTC, rynowak commented
> Can you move it into a service that is itself disposable?

No not really, it's not a singleton, and requires **data** to construct.

2019-01-14 03:47 UTC, rynowak commented
I can do something totally hack mode, by resolving another service from DI and then making that thing responsible for dispose.

2019-01-14 03:48 UTC, davidfowl approved these changes

2019-01-14 04:03 UTC, rynowak commented
Checks out my cool hack. DI is like duct tape, you can use it to fix anything.

2019-01-14 05:03 UTC, merged