Abstract ReactDevelopmentServerMiddleware to DevelopmentServerMiddleware for other NPM Web Servers
dotnet/aspnetcore pull request #7452
Opened 2019-02-11 09:43 UTC by WilliamABradley

Summary of the changes (Less than 80 chars)
Abstracted ReactDevelopmentServerMiddleware into DevelopmentServerMiddleware, obsoleted old namespace, Added Generic UseDevelopmentServer and Vue UseVueDevelopmentServer.

This opens up SpaExtensions for Vue.js as well as other npm/webpack development servers for serving UI Frameworks.

This can be used to make a Vue.js Visual Studio Template.

2019-02-23 00:10 UTC, WilliamABradley commented
@SteveSandersonMS Any news?

2019-02-25 16:24 UTC, SteveSandersonMS commented on src/Middleware/SpaServices.Extensions/src/DevelopmentServer/DevelopmentServerMiddleware.cs
> +                { "BROWSER", "none" }, // We don't want the dev server to open its own extra browser window pointing to the internal dev server port
This shouldn't be here, as it's specific to React

2019-02-25 16:25 UTC, SteveSandersonMS commented on src/Middleware/SpaServices.Extensions/src/DevelopmentServer/DevelopmentServerMiddlewareExtensions.cs
> +            string serverName = "App")
To me, these APIs feel extremely over-specialized. What if the "ready" signal isn't some static text you can look for? What if the way to start it isn't running an NPM script?

What I'd expect instead would be to decompose this into lower-level building blocks, e.g.:

 * Some method for starting an NPM script and getting back the `Process`
 * Some method for transforming the standard output stream from a `Process` into an async-enumerable-of-string
 * `UseReactDevelopmentServer` and `UseAngularCli` methods that call the "start NPM task" method, then awaits until it outputs the expected "I'm running now" string. These can each contain their own instructions to output text like "Starting Angular CLI server...", so no need to make these into parameters on something else.

2019-02-25 16:26 UTC, SteveSandersonMS commented on src/Middleware/SpaServices.Extensions/src/DevelopmentServer/DevelopmentServerMiddlewareExtensions.cs
> +        public static void UseVueDevelopmentServer(
We haven't announced any plan to build in support for Vue-specific things. Previously, we explicitly stepped away from doing that, so we could focus on the two most demanded third-party SPA frameworks (Angular and React). Changing this plan would be a decision for @danroth27.

2019-02-25 16:27 UTC, SteveSandersonMS commented on src/Middleware/SpaServices.Extensions/src/ReactDevelopmentServer/ReactDevelopmentServerMiddlewareExtensions.cs
> +        [Obsolete("Microsoft.AspNetCore.SpaServices.ReactDevelopmentServer.ReactDevelopmentServerMiddlewareExtensions.UseReactDevelopmentServer is deprecated, please use Microsoft.AspNetCore.SpaServi
Rather than obsoleting this, could the new logic go here instead of making a new extension method for it?

2019-02-25 16:29 UTC, SteveSandersonMS requested changes
Hope you don't mind these suggestions!

@ryanbrandenburg, are you interested in taking over on this PR? No worries if not - I'm happy to continue the conversation here.

2019-02-25 19:08 UTC, ryanbrandenburg commented
@SteveSandersonMS I won't have useful knowledge here until I've been brought up to speed on the whole area, so it's probably best if you stick with it for now.

2019-04-04 16:52 UTC, mkArtakMSFT commented
@SteveSandersonMS , @ryanbrandenburg what is pending here?

2019-04-04 18:08 UTC, ryanbrandenburg commented
A response to @SteveSandersonMS's request for changes. It'll also need to rebase to solve that conflict.

2019-07-04 12:34 UTC, elken commented
I've also requested this feature before (#8024), would be happy to attempt to implement @SteveSandersonMS's changes?

2019-07-24 17:25 UTC, SteveSandersonMS commented
Closing as per conversation in #11897

2019-07-24 17:25 UTC, closed without merging