[WIP] Update Mono for Blazor 0.9.0
dotnet/aspnetcore pull request #7792
Opened 2019-02-21 14:35 UTC by SteveSandersonMS

**Don't merge** - we're still investigating how this regresses the post-linked app size. Unless we find a solution to that, this probably won't be included in 0.9.0.

2019-02-22 03:09 UTC, dougbu requested changes
If this goes forward, eng/ change needs a tweak&hellip;

2019-02-22 03:09 UTC, dougbu commented on eng/Versions.props
> +    <MicrosoftAspNetCoreBlazorMonoPackageVersion>0.9.0-preview-20190221.2</MicrosoftAspNetCoreBlazorMonoPackageVersion>
Need to run `darc update-dependencies --channel ".NET Core 3 Dev" --name "Microsoft.AspNetCore.Blazor.Mono" to make corresponding update to Version.Details.xml. Or, copy the commit SHA built in 0.9.0-preview-20190221.2 manually.

2019-03-26 11:05 UTC, Suchiman commented
@SteveSandersonMS given #8782 this can be closed

2019-03-26 11:26 UTC, SteveSandersonMS commented
Correct - thanks!

2019-03-26 11:26 UTC, closed without merging