Stop running helix on PRs for now
dotnet/aspnetcore pull request #8454
Opened 2019-03-12 22:19 UTC by HaoK

2019-03-12 22:23 UTC, HaoK commented
Part of https://github.com/aspnet/AspNetCore/issues/8453

2019-03-12 23:02 UTC, dougbu approved these changes

2019-03-12 23:04 UTC, HaoK commented on .azure/pipelines/helix-test.yml
> +pr: none # will disable PR builds entirely
Yeah I noticed that too, for now I just scheduled a daily build against master that runs once a day as a starting point

2019-03-12 23:20 UTC, jkotalik requested changes
Can we please discuss this more? This will make my abilities to make any PRs for IIS incredibly hard. There is no other PR validation for IIS besides helix.

2019-03-12 23:27 UTC, jkotalik commented
@muratg @shirhatti

2019-03-12 23:45 UTC, HaoK commented
Lets use the issue for the discussion

2019-03-13 01:21 UTC, jkotalik commented on .azure/pipelines/helix-test.yml
> +pr: none # will disable PR builds entirely
Can we just narrow down the queue to only include Windows.10.Amd64.EnterpriseRS3.ASPNET.Open listed here: https://github.com/aspnet/AspNetCore/blob/master/eng/targets/Helix.Common.props#L15

2019-03-13 01:21 UTC, jkotalik commented on .azure/pipelines/helix-test.yml
> +pr: none # will disable PR builds entirely
This will give half of the IIS coverage (no coverage on IIS Express but it's better than nothing).

2019-03-13 17:09 UTC, HaoK commented
Going with https://github.com/aspnet/AspNetCore/pull/8464 instead

2019-03-13 17:09 UTC, closed without merging