Mark tests flaky instead of skipped
dotnet/aspnetcore pull request #8727
Opened 2019-03-21 23:57 UTC by ryanbrandenburg

This should make sure there's plenty to hear about once we finish https://github.com/aspnet/AspNetCore-Internal/issues/1948.

2019-03-22 00:12 UTC, BrennanConroy commented on src/SignalR/server/StackExchangeRedis/test/RedisHubLifetimeManagerTests.cs
> +        [Flaky("https://github.com/aspnet/SignalR/issues/3088")]
This one isn't flaky, it's just broken. Do we want to keep it as skip or no?

2019-03-22 00:20 UTC, jkotalik commented on src/Servers/IIS/IIS/test/Common.FunctionalTests/AppOfflineTests.cs
> +        [Flaky("https://github.com/aspnet/IISIntegration/issues/933")]
Delete this test. There has been no action on fixing https://github.com/dotnet/core-setup/issues/4646 and it isn't our problem.

2019-03-22 00:25 UTC, jkotalik requested changes

2019-03-22 00:25 UTC, jkotalik commented on src/Servers/IIS/IIS/test/Common.FunctionalTests/OutOfProcess/AspNetCorePortTests.cs
> +        [Flaky("https://github.com/aspnet/AspNetCore/issues/8329")]
Don't enable these tests. We need an SDK upgrade to enable these

2019-03-22 00:25 UTC, jkotalik commented on src/Servers/IIS/IIS/test/Common.FunctionalTests/OutOfProcess/HelloWorldTest.cs
> -        [ConditionalTheory(Skip = "https://github.com/aspnet/AspNetCore/issues/8329")]
These too.

2019-03-22 00:25 UTC, jkotalik commented on src/Servers/IIS/IIS/test/IIS.Tests/ClientDisconnectTests.cs
> +        [Fact]
These need to be ConditionalFacts still. There are conditions applied on the entire assembly to check whether we are running on a machine that supports this test.

2019-03-22 00:25 UTC, jkotalik commented on src/Servers/IIS/IIS/test/IISExpress.FunctionalTests/OutOfProcess/NtlmAuthentationTest.cs
> +        [Flaky("https://github.com/aspnet/AspNetCore/issues/8329")]
These three. At this point I think you can just undo all changes to the src/Servers/IIS subfolder.

2019-03-22 00:25 UTC, jkotalik commented on src/Servers/IIS/IIS/test/Common.FunctionalTests/OutOfProcess/AspNetCorePortTests.cs
> +        [Flaky("https://github.com/aspnet/AspNetCore/issues/8329")]
https://github.com/aspnet/AspNetCore/issues/8329

2019-03-22 15:21 UTC, Tratcher commented
How many of these fail every time? Not much point in marking them as flaky.

2019-03-22 15:28 UTC, anurse commented
I think we should review all the ones we know about and keep the “consistently broken” ones as Skipped (or delete them). There are bound to be ones we don’t know/remember well though. Might be worth doing a survey of the flaky tests in, say, a week and for any of them that have never passed in that time, switch them back to fully skipped. Thoughts?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-03-22 22:24 UTC, ryanbrandenburg commented
I was going to go with "unskip everything and let it make noise" but I'm fine with leaving consistently failing ones out.

2019-03-22 23:04 UTC, ryanbrandenburg commented
:up::date: I reviewed the issues and left the ones that claim to fail every time as skipped.

2019-03-22 23:07 UTC, BrennanConroy approved these changes
Good from SignalR and dotnet-watch side

2019-03-22 23:10 UTC, Tratcher approved these changes

2019-03-22 23:18 UTC, jkotalik approved these changes

2019-03-25 19:05 UTC, Tratcher approved these changes

2019-03-25 19:05 UTC, Tratcher commented on src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TimeoutTests.cs
> +            var limits = _serviceContext.ServerOptions.Limits; ;
```suggestion
            var limits = _serviceContext.ServerOptions.Limits;
```

2019-03-26 16:51 UTC, merged