Make some skipped tests flaky
dotnet/aspnetcore pull request #8795
Opened 2019-03-25 18:22 UTC by ryanbrandenburg

2019-03-25 18:32 UTC, Tratcher requested changes

2019-03-25 18:32 UTC, Tratcher commented on src/Hosting/test/FunctionalTests/ShutdownTests.cs
> +        [Flaky("https://github.com/aspnet/AspNetCore-Internal/issues/1687", FlakyOn.AzP.Linux)]
Revert. These tests are currently only designed for linux.

2019-03-25 18:32 UTC, Tratcher commented on src/Hosting/test/FunctionalTests/ShutdownTests.cs
> +        [Flaky("https://github.com/aspnet/Hosting/issues/1214", FlakyOn.AzP.Windows, FlakyOn.AzP.macOS)]
Still skip on Windows an Mac for design reasons, not for flakyness.

2019-03-25 19:06 UTC, ryanbrandenburg commented
:up::date:

2019-03-26 18:49 UTC, ryanbrandenburg commented
:up::date:

2019-03-26 20:06 UTC, halter73 approved these changes

2019-03-27 17:14 UTC, Tratcher approved these changes

2019-03-27 17:20 UTC, merged