Make some tests Flaky
dotnet/aspnetcore pull request #9935
Opened 2019-05-02 22:18 UTC by ryanbrandenburg

2019-05-02 22:21 UTC, jkotalik approved these changes

2019-05-03 17:08 UTC, pranavkm requested changes

2019-05-03 17:08 UTC, pranavkm commented on src/Identity/test/Identity.Test/IdentityUIScriptsTest.cs
> +        [Flaky("https://github.com/aspnet/AspNetCore-Internal/issues/2267", FlakyOn.All)]
The test's failed only on MacOS. Can we limit it to that platform?

2019-05-03 21:21 UTC, pranavkm approved these changes

2019-05-06 22:33 UTC, merged